//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:48 ÏÂÎç CST 
//


package com.faurecia.model.delfor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Last Deliveries
 * 
 * <p>Java class for DELFOR02.E1EDP36 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELFOR02.E1EDP36">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LIFST" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BELNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BELDAT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BELTIM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LFIMG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VRKME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VEMNG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIKME" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIDTL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIDTIM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELFOR02.E1EDP36", propOrder = {
    "lifst",
    "belnr",
    "beldat",
    "beltim",
    "lfimg",
    "vrkme",
    "vemng",
    "likme",
    "lidtl",
    "lidtim"
})
public class DELFOR02E1EDP36 {

    @XmlElement(name = "LIFST")
    protected String lifst;
    @XmlElement(name = "BELNR")
    protected String belnr;
    @XmlElement(name = "BELDAT")
    protected String beldat;
    @XmlElement(name = "BELTIM")
    protected String beltim;
    @XmlElement(name = "LFIMG")
    protected String lfimg;
    @XmlElement(name = "VRKME")
    protected String vrkme;
    @XmlElement(name = "VEMNG")
    protected String vemng;
    @XmlElement(name = "LIKME")
    protected String likme;
    @XmlElement(name = "LIDTL")
    protected String lidtl;
    @XmlElement(name = "LIDTIM")
    protected String lidtim;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the lifst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIFST() {
        return lifst;
    }

    /**
     * Sets the value of the lifst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIFST(String value) {
        this.lifst = value;
    }

    /**
     * Gets the value of the belnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBELNR() {
        return belnr;
    }

    /**
     * Sets the value of the belnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBELNR(String value) {
        this.belnr = value;
    }

    /**
     * Gets the value of the beldat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBELDAT() {
        return beldat;
    }

    /**
     * Sets the value of the beldat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBELDAT(String value) {
        this.beldat = value;
    }

    /**
     * Gets the value of the beltim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBELTIM() {
        return beltim;
    }

    /**
     * Sets the value of the beltim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBELTIM(String value) {
        this.beltim = value;
    }

    /**
     * Gets the value of the lfimg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLFIMG() {
        return lfimg;
    }

    /**
     * Sets the value of the lfimg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLFIMG(String value) {
        this.lfimg = value;
    }

    /**
     * Gets the value of the vrkme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVRKME() {
        return vrkme;
    }

    /**
     * Sets the value of the vrkme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVRKME(String value) {
        this.vrkme = value;
    }

    /**
     * Gets the value of the vemng property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVEMNG() {
        return vemng;
    }

    /**
     * Sets the value of the vemng property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVEMNG(String value) {
        this.vemng = value;
    }

    /**
     * Gets the value of the likme property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIKME() {
        return likme;
    }

    /**
     * Sets the value of the likme property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIKME(String value) {
        this.likme = value;
    }

    /**
     * Gets the value of the lidtl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIDTL() {
        return lidtl;
    }

    /**
     * Sets the value of the lidtl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIDTL(String value) {
        this.lidtl = value;
    }

    /**
     * Gets the value of the lidtim property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIDTIM() {
        return lidtim;
    }

    /**
     * Sets the value of the lidtim property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIDTIM(String value) {
        this.lidtim = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
