//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * DG item data descriptions 2 (delivery)
 * 
 * <p>Java class for DELVRY03.E1EDD15 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDD15">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="HPN1D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN2D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN3D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN4D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN5D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN6D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPN7D" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDD15", propOrder = {
    "hpn1D",
    "hpn2D",
    "hpn3D",
    "hpn4D",
    "hpn5D",
    "hpn6D",
    "hpn7D"
})
public class DELVRY03E1EDD15 {

    @XmlElement(name = "HPN1D")
    protected String hpn1D;
    @XmlElement(name = "HPN2D")
    protected String hpn2D;
    @XmlElement(name = "HPN3D")
    protected String hpn3D;
    @XmlElement(name = "HPN4D")
    protected String hpn4D;
    @XmlElement(name = "HPN5D")
    protected String hpn5D;
    @XmlElement(name = "HPN6D")
    protected String hpn6D;
    @XmlElement(name = "HPN7D")
    protected String hpn7D;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the hpn1D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN1D() {
        return hpn1D;
    }

    /**
     * Sets the value of the hpn1D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN1D(String value) {
        this.hpn1D = value;
    }

    /**
     * Gets the value of the hpn2D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN2D() {
        return hpn2D;
    }

    /**
     * Sets the value of the hpn2D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN2D(String value) {
        this.hpn2D = value;
    }

    /**
     * Gets the value of the hpn3D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN3D() {
        return hpn3D;
    }

    /**
     * Sets the value of the hpn3D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN3D(String value) {
        this.hpn3D = value;
    }

    /**
     * Gets the value of the hpn4D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN4D() {
        return hpn4D;
    }

    /**
     * Sets the value of the hpn4D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN4D(String value) {
        this.hpn4D = value;
    }

    /**
     * Gets the value of the hpn5D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN5D() {
        return hpn5D;
    }

    /**
     * Sets the value of the hpn5D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN5D(String value) {
        this.hpn5D = value;
    }

    /**
     * Gets the value of the hpn6D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN6D() {
        return hpn6D;
    }

    /**
     * Sets the value of the hpn6D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN6D(String value) {
        this.hpn6D = value;
    }

    /**
     * Gets the value of the hpn7D property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPN7D() {
        return hpn7D;
    }

    /**
     * Sets the value of the hpn7D property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPN7D(String value) {
        this.hpn7D = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
