//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.03 at 02:17:36 ÏÂÎç CST 
//


package com.faurecia.model.order;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Purchasing/Sales
 * 
 * <p>Java class for ORDERS.ORDERS02 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ORDERS.ORDERS02">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EDI_DC40" type="{}EDI_DC40.ORDERS.ORDERS02"/>
 *         &lt;element name="E1EDK01" type="{}ORDERS02.E1EDK01"/>
 *         &lt;element name="E1EDK14" type="{}ORDERS02.E1EDK14" maxOccurs="12" minOccurs="0"/>
 *         &lt;element name="E1EDK03" type="{}ORDERS02.E1EDK03" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="E1EDK04" type="{}ORDERS02.E1EDK04" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="E1EDK05" type="{}ORDERS02.E1EDK05" maxOccurs="16" minOccurs="0"/>
 *         &lt;element name="E1EDKA1" type="{}ORDERS02.E1EDKA1" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="E1EDK02" type="{}ORDERS02.E1EDK02" maxOccurs="10" minOccurs="0"/>
 *         &lt;element name="E1EDK17" type="{}ORDERS02.E1EDK17" maxOccurs="4" minOccurs="0"/>
 *         &lt;element name="E1EDK18" type="{}ORDERS02.E1EDK18" maxOccurs="3" minOccurs="0"/>
 *         &lt;element name="E1EDK35" type="{}ORDERS02.E1EDK35" maxOccurs="99999" minOccurs="0"/>
 *         &lt;element name="E1EDK36" type="{}ORDERS02.E1EDK36" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="E1EDKT1" type="{}ORDERS02.E1EDKT1" maxOccurs="99" minOccurs="0"/>
 *         &lt;element name="E1EDP01" type="{}ORDERS02.E1EDP01" maxOccurs="999999" minOccurs="0"/>
 *         &lt;element name="E1CUCFG" type="{}ORDERS02.E1CUCFG" maxOccurs="99999" minOccurs="0"/>
 *         &lt;element name="E1EDL37" type="{}ORDERS02.E1EDL37" maxOccurs="999999" minOccurs="0"/>
 *         &lt;element name="E1EDS01" type="{}ORDERS02.E1EDS01" maxOccurs="5" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="BEGIN" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ORDERS.ORDERS02", propOrder = {
    "edidc40",
    "e1EDK01",
    "e1EDK14",
    "e1EDK03",
    "e1EDK04",
    "e1EDK05",
    "e1EDKA1",
    "e1EDK02",
    "e1EDK17",
    "e1EDK18",
    "e1EDK35",
    "e1EDK36",
    "e1EDKT1",
    "e1EDP01",
    "e1CUCFG",
    "e1EDL37",
    "e1EDS01"
})
public class ORDERSORDERS02 {

    @XmlElement(name = "EDI_DC40", required = true)
    protected EDIDC40ORDERSORDERS02 edidc40;
    @XmlElement(name = "E1EDK01", required = true)
    protected ORDERS02E1EDK01 e1EDK01;
    @XmlElement(name = "E1EDK14")
    protected List<ORDERS02E1EDK14> e1EDK14;
    @XmlElement(name = "E1EDK03")
    protected List<ORDERS02E1EDK03> e1EDK03;
    @XmlElement(name = "E1EDK04")
    protected List<ORDERS02E1EDK04> e1EDK04;
    @XmlElement(name = "E1EDK05")
    protected List<ORDERS02E1EDK05> e1EDK05;
    @XmlElement(name = "E1EDKA1")
    protected List<ORDERS02E1EDKA1> e1EDKA1;
    @XmlElement(name = "E1EDK02")
    protected List<ORDERS02E1EDK02> e1EDK02;
    @XmlElement(name = "E1EDK17")
    protected List<ORDERS02E1EDK17> e1EDK17;
    @XmlElement(name = "E1EDK18")
    protected List<ORDERS02E1EDK18> e1EDK18;
    @XmlElement(name = "E1EDK35")
    protected List<ORDERS02E1EDK35> e1EDK35;
    @XmlElement(name = "E1EDK36")
    protected List<ORDERS02E1EDK36> e1EDK36;
    @XmlElement(name = "E1EDKT1")
    protected List<ORDERS02E1EDKT1> e1EDKT1;
    @XmlElement(name = "E1EDP01")
    protected List<ORDERS02E1EDP01> e1EDP01;
    @XmlElement(name = "E1CUCFG")
    protected List<ORDERS02E1CUCFG> e1CUCFG;
    @XmlElement(name = "E1EDL37")
    protected List<ORDERS02E1EDL37> e1EDL37;
    @XmlElement(name = "E1EDS01")
    protected List<ORDERS02E1EDS01> e1EDS01;
    @XmlAttribute(name = "BEGIN", required = true)
    protected String begin;

    /**
     * Gets the value of the edidc40 property.
     * 
     * @return
     *     possible object is
     *     {@link EDIDC40ORDERSORDERS02 }
     *     
     */
    public EDIDC40ORDERSORDERS02 getEDIDC40() {
        return edidc40;
    }

    /**
     * Sets the value of the edidc40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link EDIDC40ORDERSORDERS02 }
     *     
     */
    public void setEDIDC40(EDIDC40ORDERSORDERS02 value) {
        this.edidc40 = value;
    }

    /**
     * Gets the value of the e1EDK01 property.
     * 
     * @return
     *     possible object is
     *     {@link ORDERS02E1EDK01 }
     *     
     */
    public ORDERS02E1EDK01 getE1EDK01() {
        return e1EDK01;
    }

    /**
     * Sets the value of the e1EDK01 property.
     * 
     * @param value
     *     allowed object is
     *     {@link ORDERS02E1EDK01 }
     *     
     */
    public void setE1EDK01(ORDERS02E1EDK01 value) {
        this.e1EDK01 = value;
    }

    /**
     * Gets the value of the e1EDK14 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK14 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK14().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK14 }
     * 
     * 
     */
    public List<ORDERS02E1EDK14> getE1EDK14() {
        if (e1EDK14 == null) {
            e1EDK14 = new ArrayList<ORDERS02E1EDK14>();
        }
        return this.e1EDK14;
    }

    /**
     * Gets the value of the e1EDK03 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK03 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK03().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK03 }
     * 
     * 
     */
    public List<ORDERS02E1EDK03> getE1EDK03() {
        if (e1EDK03 == null) {
            e1EDK03 = new ArrayList<ORDERS02E1EDK03>();
        }
        return this.e1EDK03;
    }

    /**
     * Gets the value of the e1EDK04 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK04 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK04().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK04 }
     * 
     * 
     */
    public List<ORDERS02E1EDK04> getE1EDK04() {
        if (e1EDK04 == null) {
            e1EDK04 = new ArrayList<ORDERS02E1EDK04>();
        }
        return this.e1EDK04;
    }

    /**
     * Gets the value of the e1EDK05 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK05 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK05().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK05 }
     * 
     * 
     */
    public List<ORDERS02E1EDK05> getE1EDK05() {
        if (e1EDK05 == null) {
            e1EDK05 = new ArrayList<ORDERS02E1EDK05>();
        }
        return this.e1EDK05;
    }

    /**
     * Gets the value of the e1EDKA1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDKA1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDKA1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDKA1 }
     * 
     * 
     */
    public List<ORDERS02E1EDKA1> getE1EDKA1() {
        if (e1EDKA1 == null) {
            e1EDKA1 = new ArrayList<ORDERS02E1EDKA1>();
        }
        return this.e1EDKA1;
    }

    /**
     * Gets the value of the e1EDK02 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK02 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK02().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK02 }
     * 
     * 
     */
    public List<ORDERS02E1EDK02> getE1EDK02() {
        if (e1EDK02 == null) {
            e1EDK02 = new ArrayList<ORDERS02E1EDK02>();
        }
        return this.e1EDK02;
    }

    /**
     * Gets the value of the e1EDK17 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK17 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK17().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK17 }
     * 
     * 
     */
    public List<ORDERS02E1EDK17> getE1EDK17() {
        if (e1EDK17 == null) {
            e1EDK17 = new ArrayList<ORDERS02E1EDK17>();
        }
        return this.e1EDK17;
    }

    /**
     * Gets the value of the e1EDK18 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK18 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK18().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK18 }
     * 
     * 
     */
    public List<ORDERS02E1EDK18> getE1EDK18() {
        if (e1EDK18 == null) {
            e1EDK18 = new ArrayList<ORDERS02E1EDK18>();
        }
        return this.e1EDK18;
    }

    /**
     * Gets the value of the e1EDK35 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK35 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK35().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK35 }
     * 
     * 
     */
    public List<ORDERS02E1EDK35> getE1EDK35() {
        if (e1EDK35 == null) {
            e1EDK35 = new ArrayList<ORDERS02E1EDK35>();
        }
        return this.e1EDK35;
    }

    /**
     * Gets the value of the e1EDK36 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDK36 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDK36().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDK36 }
     * 
     * 
     */
    public List<ORDERS02E1EDK36> getE1EDK36() {
        if (e1EDK36 == null) {
            e1EDK36 = new ArrayList<ORDERS02E1EDK36>();
        }
        return this.e1EDK36;
    }

    /**
     * Gets the value of the e1EDKT1 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDKT1 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDKT1().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDKT1 }
     * 
     * 
     */
    public List<ORDERS02E1EDKT1> getE1EDKT1() {
        if (e1EDKT1 == null) {
            e1EDKT1 = new ArrayList<ORDERS02E1EDKT1>();
        }
        return this.e1EDKT1;
    }

    /**
     * Gets the value of the e1EDP01 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDP01 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDP01().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDP01 }
     * 
     * 
     */
    public List<ORDERS02E1EDP01> getE1EDP01() {
        if (e1EDP01 == null) {
            e1EDP01 = new ArrayList<ORDERS02E1EDP01>();
        }
        return this.e1EDP01;
    }

    /**
     * Gets the value of the e1CUCFG property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1CUCFG property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1CUCFG().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1CUCFG }
     * 
     * 
     */
    public List<ORDERS02E1CUCFG> getE1CUCFG() {
        if (e1CUCFG == null) {
            e1CUCFG = new ArrayList<ORDERS02E1CUCFG>();
        }
        return this.e1CUCFG;
    }

    /**
     * Gets the value of the e1EDL37 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDL37 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDL37().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDL37 }
     * 
     * 
     */
    public List<ORDERS02E1EDL37> getE1EDL37() {
        if (e1EDL37 == null) {
            e1EDL37 = new ArrayList<ORDERS02E1EDL37>();
        }
        return this.e1EDL37;
    }

    /**
     * Gets the value of the e1EDS01 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1EDS01 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1EDS01().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ORDERS02E1EDS01 }
     * 
     * 
     */
    public List<ORDERS02E1EDS01> getE1EDS01() {
        if (e1EDS01 == null) {
            e1EDS01 = new ArrayList<ORDERS02E1EDS01>();
        }
        return this.e1EDS01;
    }

    /**
     * Gets the value of the begin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBEGIN() {
        if (begin == null) {
            return "1";
        } else {
            return begin;
        }
    }

    /**
     * Sets the value of the begin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBEGIN(String value) {
        this.begin = value;
    }

}
