//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.03 at 02:17:36 ÏÂÎç CST 
//


package com.faurecia.model.order;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * IDoc: Document Item Object Identification
 * 
 * <p>Java class for ORDERS02.E1EDP19 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ORDERS02.E1EDP19">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QUALF" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IDTNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KTEXT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="70"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MFRPN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="42"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MFRNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IDTNR_EXTERNAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IDTNR_VERSION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IDTNR_GUID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ORDERS02.E1EDP19", propOrder = {
    "qualf",
    "idtnr",
    "ktext",
    "mfrpn",
    "mfrnr",
    "idtnrexternal",
    "idtnrversion",
    "idtnrguid"
})
public class ORDERS02E1EDP19 {

    @XmlElement(name = "QUALF")
    protected String qualf;
    @XmlElement(name = "IDTNR")
    protected String idtnr;
    @XmlElement(name = "KTEXT")
    protected String ktext;
    @XmlElement(name = "MFRPN")
    protected String mfrpn;
    @XmlElement(name = "MFRNR")
    protected String mfrnr;
    @XmlElement(name = "IDTNR_EXTERNAL")
    protected String idtnrexternal;
    @XmlElement(name = "IDTNR_VERSION")
    protected String idtnrversion;
    @XmlElement(name = "IDTNR_GUID")
    protected String idtnrguid;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the qualf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALF() {
        return qualf;
    }

    /**
     * Sets the value of the qualf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALF(String value) {
        this.qualf = value;
    }

    /**
     * Gets the value of the idtnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTNR() {
        return idtnr;
    }

    /**
     * Sets the value of the idtnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTNR(String value) {
        this.idtnr = value;
    }

    /**
     * Gets the value of the ktext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKTEXT() {
        return ktext;
    }

    /**
     * Sets the value of the ktext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKTEXT(String value) {
        this.ktext = value;
    }

    /**
     * Gets the value of the mfrpn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFRPN() {
        return mfrpn;
    }

    /**
     * Sets the value of the mfrpn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFRPN(String value) {
        this.mfrpn = value;
    }

    /**
     * Gets the value of the mfrnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMFRNR() {
        return mfrnr;
    }

    /**
     * Sets the value of the mfrnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMFRNR(String value) {
        this.mfrnr = value;
    }

    /**
     * Gets the value of the idtnrexternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTNREXTERNAL() {
        return idtnrexternal;
    }

    /**
     * Sets the value of the idtnrexternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTNREXTERNAL(String value) {
        this.idtnrexternal = value;
    }

    /**
     * Gets the value of the idtnrversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTNRVERSION() {
        return idtnrversion;
    }

    /**
     * Sets the value of the idtnrversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTNRVERSION(String value) {
        this.idtnrversion = value;
    }

    /**
     * Gets the value of the idtnrguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDTNRGUID() {
        return idtnrguid;
    }

    /**
     * Sets the value of the idtnrguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDTNRGUID(String value) {
        this.idtnrguid = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
