//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:25:07 ÏÂÎç CST 
//


package com.faurecia.model.order;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.faurecia.model.order package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.faurecia.model.order
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ORDERS05E1ADDI1 }
     * 
     */
    public ORDERS05E1ADDI1 createORDERS05E1ADDI1() {
        return new ORDERS05E1ADDI1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC18 }
     * 
     */
    public ORDERS05E1EDC18 createORDERS05E1EDC18() {
        return new ORDERS05E1EDC18();
    }

    /**
     * Create an instance of {@link EDIDC40ORDERSORDERS05 }
     * 
     */
    public EDIDC40ORDERSORDERS05 createEDIDC40ORDERSORDERS05() {
        return new EDIDC40ORDERSORDERS05();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPAD }
     * 
     */
    public ORDERS05E1EDPAD createORDERS05E1EDPAD() {
        return new ORDERS05E1EDPAD();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK35 }
     * 
     */
    public ORDERS05E1EDK35 createORDERS05E1EDK35() {
        return new ORDERS05E1EDK35();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUCFG }
     * 
     */
    public ORDERS05E1CUCFG createORDERS05E1CUCFG() {
        return new ORDERS05E1CUCFG();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP02 }
     * 
     */
    public ORDERS05E1EDP02 createORDERS05E1EDP02() {
        return new ORDERS05E1EDP02();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK05 }
     * 
     */
    public ORDERS05E1EDK05 createORDERS05E1EDK05() {
        return new ORDERS05E1EDK05();
    }

    /**
     * Create an instance of {@link ORDERS05E1TXTH1 }
     * 
     */
    public ORDERS05E1TXTH1 createORDERS05E1TXTH1() {
        return new ORDERS05E1TXTH1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDKT1 }
     * 
     */
    public ORDERS05E1EDKT1 createORDERS05E1EDKT1() {
        return new ORDERS05E1EDKT1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDCT2 }
     * 
     */
    public ORDERS05E1EDCT2 createORDERS05E1EDCT2() {
        return new ORDERS05E1EDCT2();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK17 }
     * 
     */
    public ORDERS05E1EDK17 createORDERS05E1EDK17() {
        return new ORDERS05E1EDK17();
    }

    /**
     * Create an instance of {@link ORDERS05E1TXTP1 }
     * 
     */
    public ORDERS05E1TXTP1 createORDERS05E1TXTP1() {
        return new ORDERS05E1TXTP1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK03 }
     * 
     */
    public ORDERS05E1EDK03 createORDERS05E1EDK03() {
        return new ORDERS05E1EDK03();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC01 }
     * 
     */
    public ORDERS05E1EDC01 createORDERS05E1EDC01() {
        return new ORDERS05E1EDC01();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC03 }
     * 
     */
    public ORDERS05E1EDC03 createORDERS05E1EDC03() {
        return new ORDERS05E1EDC03();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPS5 }
     * 
     */
    public ORDERS05E1EDPS5 createORDERS05E1EDPS5() {
        return new ORDERS05E1EDPS5();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDL44 }
     * 
     */
    public ORDERS05E1EDL44 createORDERS05E1EDL44() {
        return new ORDERS05E1EDL44();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP19 }
     * 
     */
    public ORDERS05E1EDP19 createORDERS05E1EDP19() {
        return new ORDERS05E1EDP19();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP01 }
     * 
     */
    public ORDERS05E1EDP01 createORDERS05E1EDP01() {
        return new ORDERS05E1EDP01();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP17 }
     * 
     */
    public ORDERS05E1EDP17 createORDERS05E1EDP17() {
        return new ORDERS05E1EDP17();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDL39 }
     * 
     */
    public ORDERS05E1EDL39 createORDERS05E1EDL39() {
        return new ORDERS05E1EDL39();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP20 }
     * 
     */
    public ORDERS05E1EDP20 createORDERS05E1EDP20() {
        return new ORDERS05E1EDP20();
    }

    /**
     * Create an instance of {@link ORDERS05 }
     * 
     */
    public ORDERS05 createORDERS05() {
        return new ORDERS05();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC19 }
     * 
     */
    public ORDERS05E1EDC19 createORDERS05E1EDC19() {
        return new ORDERS05E1EDC19();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDL37 }
     * 
     */
    public ORDERS05E1EDL37 createORDERS05E1EDL37() {
        return new ORDERS05E1EDL37();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUVAL }
     * 
     */
    public ORDERS05E1CUVAL createORDERS05E1CUVAL() {
        return new ORDERS05E1CUVAL();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPA1 }
     * 
     */
    public ORDERS05E1EDPA1 createORDERS05E1EDPA1() {
        return new ORDERS05E1EDPA1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC05 }
     * 
     */
    public ORDERS05E1EDC05 createORDERS05E1EDC05() {
        return new ORDERS05E1EDC05();
    }

    /**
     * Create an instance of {@link ORDERSORDERS05 }
     * 
     */
    public ORDERSORDERS05 createORDERSORDERS05() {
        return new ORDERSORDERS05();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK14 }
     * 
     */
    public ORDERS05E1EDK14 createORDERS05E1EDK14() {
        return new ORDERS05E1EDK14();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP35 }
     * 
     */
    public ORDERS05E1EDP35 createORDERS05E1EDP35() {
        return new ORDERS05E1EDP35();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK02 }
     * 
     */
    public ORDERS05E1EDK02 createORDERS05E1EDK02() {
        return new ORDERS05E1EDK02();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK36 }
     * 
     */
    public ORDERS05E1EDK36 createORDERS05E1EDK36() {
        return new ORDERS05E1EDK36();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUBLB }
     * 
     */
    public ORDERS05E1CUBLB createORDERS05E1CUBLB() {
        return new ORDERS05E1CUBLB();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPA3 }
     * 
     */
    public ORDERS05E1EDPA3 createORDERS05E1EDPA3() {
        return new ORDERS05E1EDPA3();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC17 }
     * 
     */
    public ORDERS05E1EDC17 createORDERS05E1EDC17() {
        return new ORDERS05E1EDC17();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP18 }
     * 
     */
    public ORDERS05E1EDP18 createORDERS05E1EDP18() {
        return new ORDERS05E1EDP18();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC06 }
     * 
     */
    public ORDERS05E1EDC06 createORDERS05E1EDC06() {
        return new ORDERS05E1EDC06();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDL38 }
     * 
     */
    public ORDERS05E1EDL38 createORDERS05E1EDL38() {
        return new ORDERS05E1EDL38();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK04 }
     * 
     */
    public ORDERS05E1EDK04 createORDERS05E1EDK04() {
        return new ORDERS05E1EDK04();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPT2 }
     * 
     */
    public ORDERS05E1EDPT2 createORDERS05E1EDPT2() {
        return new ORDERS05E1EDPT2();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK18 }
     * 
     */
    public ORDERS05E1EDK18 createORDERS05E1EDK18() {
        return new ORDERS05E1EDK18();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDCA1 }
     * 
     */
    public ORDERS05E1EDCA1 createORDERS05E1EDCA1() {
        return new ORDERS05E1EDCA1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC04 }
     * 
     */
    public ORDERS05E1EDC04 createORDERS05E1EDC04() {
        return new ORDERS05E1EDC04();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC07 }
     * 
     */
    public ORDERS05E1EDC07 createORDERS05E1EDC07() {
        return new ORDERS05E1EDC07();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDKA1 }
     * 
     */
    public ORDERS05E1EDKA1 createORDERS05E1EDKA1() {
        return new ORDERS05E1EDKA1();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUPRT }
     * 
     */
    public ORDERS05E1CUPRT createORDERS05E1CUPRT() {
        return new ORDERS05E1CUPRT();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUINS }
     * 
     */
    public ORDERS05E1CUINS createORDERS05E1CUINS() {
        return new ORDERS05E1CUINS();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDKT2 }
     * 
     */
    public ORDERS05E1EDKT2 createORDERS05E1EDKT2() {
        return new ORDERS05E1EDKT2();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDK01 }
     * 
     */
    public ORDERS05E1EDK01 createORDERS05E1EDK01() {
        return new ORDERS05E1EDK01();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP05 }
     * 
     */
    public ORDERS05E1EDP05 createORDERS05E1EDP05() {
        return new ORDERS05E1EDP05();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDS01 }
     * 
     */
    public ORDERS05E1EDS01 createORDERS05E1EDS01() {
        return new ORDERS05E1EDS01();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDPT1 }
     * 
     */
    public ORDERS05E1EDPT1 createORDERS05E1EDPT1() {
        return new ORDERS05E1EDPT1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP03 }
     * 
     */
    public ORDERS05E1EDP03 createORDERS05E1EDP03() {
        return new ORDERS05E1EDP03();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDC02 }
     * 
     */
    public ORDERS05E1EDC02 createORDERS05E1EDC02() {
        return new ORDERS05E1EDC02();
    }

    /**
     * Create an instance of {@link ORDERS05E1CUREF }
     * 
     */
    public ORDERS05E1CUREF createORDERS05E1CUREF() {
        return new ORDERS05E1CUREF();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDP04 }
     * 
     */
    public ORDERS05E1EDP04 createORDERS05E1EDP04() {
        return new ORDERS05E1EDP04();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDCT1 }
     * 
     */
    public ORDERS05E1EDCT1 createORDERS05E1EDCT1() {
        return new ORDERS05E1EDCT1();
    }

    /**
     * Create an instance of {@link ORDERS05E1EDKA3 }
     * 
     */
    public ORDERS05E1EDKA3 createORDERS05E1EDKA3() {
        return new ORDERS05E1EDKA3();
    }

}
