//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.01 at 08:25:51 ÏÂÎç CST 
//


package com.faurecia.model.mbgmcr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDOC" type="{}MBGMCR.MBGMCR02"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "idoc"
})
@XmlRootElement(name = "MBGMCR02")
public class MBGMCR02 {

    @XmlElement(name = "IDOC", required = true)
    protected MBGMCRMBGMCR02 idoc;

    /**
     * Gets the value of the idoc property.
     * 
     * @return
     *     possible object is
     *     {@link MBGMCRMBGMCR02 }
     *     
     */
    public MBGMCRMBGMCR02 getIDOC() {
        return idoc;
    }

    /**
     * Sets the value of the idoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBGMCRMBGMCR02 }
     *     
     */
    public void setIDOC(MBGMCRMBGMCR02 value) {
        this.idoc = value;
    }

}
