//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Export Data Delivery Header Descriptions
 * 
 * <p>Java class for DELVRY03.E1EDL34 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDL34">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="EXPVZ_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLLA_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLLB_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL1_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL2_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL3_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL4_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL5_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ZOLL6_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IEVER_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGBE_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STABE_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDL34", propOrder = {
    "expvzbez",
    "zollabez",
    "zollbbez",
    "zoll1BEZ",
    "zoll2BEZ",
    "zoll3BEZ",
    "zoll4BEZ",
    "zoll5BEZ",
    "zoll6BEZ",
    "ieverbez",
    "stgbebez",
    "stabebez"
})
public class DELVRY03E1EDL34 {

    @XmlElement(name = "EXPVZ_BEZ")
    protected String expvzbez;
    @XmlElement(name = "ZOLLA_BEZ")
    protected String zollabez;
    @XmlElement(name = "ZOLLB_BEZ")
    protected String zollbbez;
    @XmlElement(name = "ZOLL1_BEZ")
    protected String zoll1BEZ;
    @XmlElement(name = "ZOLL2_BEZ")
    protected String zoll2BEZ;
    @XmlElement(name = "ZOLL3_BEZ")
    protected String zoll3BEZ;
    @XmlElement(name = "ZOLL4_BEZ")
    protected String zoll4BEZ;
    @XmlElement(name = "ZOLL5_BEZ")
    protected String zoll5BEZ;
    @XmlElement(name = "ZOLL6_BEZ")
    protected String zoll6BEZ;
    @XmlElement(name = "IEVER_BEZ")
    protected String ieverbez;
    @XmlElement(name = "STGBE_BEZ")
    protected String stgbebez;
    @XmlElement(name = "STABE_BEZ")
    protected String stabebez;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the expvzbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPVZBEZ() {
        return expvzbez;
    }

    /**
     * Sets the value of the expvzbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPVZBEZ(String value) {
        this.expvzbez = value;
    }

    /**
     * Gets the value of the zollabez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLLABEZ() {
        return zollabez;
    }

    /**
     * Sets the value of the zollabez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLLABEZ(String value) {
        this.zollabez = value;
    }

    /**
     * Gets the value of the zollbbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLLBBEZ() {
        return zollbbez;
    }

    /**
     * Sets the value of the zollbbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLLBBEZ(String value) {
        this.zollbbez = value;
    }

    /**
     * Gets the value of the zoll1BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL1BEZ() {
        return zoll1BEZ;
    }

    /**
     * Sets the value of the zoll1BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL1BEZ(String value) {
        this.zoll1BEZ = value;
    }

    /**
     * Gets the value of the zoll2BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL2BEZ() {
        return zoll2BEZ;
    }

    /**
     * Sets the value of the zoll2BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL2BEZ(String value) {
        this.zoll2BEZ = value;
    }

    /**
     * Gets the value of the zoll3BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL3BEZ() {
        return zoll3BEZ;
    }

    /**
     * Sets the value of the zoll3BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL3BEZ(String value) {
        this.zoll3BEZ = value;
    }

    /**
     * Gets the value of the zoll4BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL4BEZ() {
        return zoll4BEZ;
    }

    /**
     * Sets the value of the zoll4BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL4BEZ(String value) {
        this.zoll4BEZ = value;
    }

    /**
     * Gets the value of the zoll5BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL5BEZ() {
        return zoll5BEZ;
    }

    /**
     * Sets the value of the zoll5BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL5BEZ(String value) {
        this.zoll5BEZ = value;
    }

    /**
     * Gets the value of the zoll6BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getZOLL6BEZ() {
        return zoll6BEZ;
    }

    /**
     * Sets the value of the zoll6BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setZOLL6BEZ(String value) {
        this.zoll6BEZ = value;
    }

    /**
     * Gets the value of the ieverbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIEVERBEZ() {
        return ieverbez;
    }

    /**
     * Sets the value of the ieverbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIEVERBEZ(String value) {
        this.ieverbez = value;
    }

    /**
     * Gets the value of the stgbebez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGBEBEZ() {
        return stgbebez;
    }

    /**
     * Sets the value of the stgbebez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGBEBEZ(String value) {
        this.stgbebez = value;
    }

    /**
     * Gets the value of the stabebez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTABEBEZ() {
        return stabebez;
    }

    /**
     * Sets the value of the stabebez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTABEBEZ(String value) {
        this.stabebez = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
