//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Route Stage Point
 * 
 * <p>Java class for DELVRY03.E1EDL32 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDL32">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QUALI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KNOTE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ADRNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSTEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LSTEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WERKS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LGORT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KUNNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIFNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ABLAD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LGNUM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LGTOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="E1EDL45" type="{}DELVRY03.E1EDL45" minOccurs="0"/>
 *         &lt;element name="E1ADRM3" type="{}DELVRY03.E1ADRM3" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDL32", propOrder = {
    "quali",
    "knote",
    "adrnr",
    "vstel",
    "lstel",
    "werks",
    "lgort",
    "kunnr",
    "lifnr",
    "ablad",
    "lgnum",
    "lgtor",
    "e1EDL45",
    "e1ADRM3"
})
public class DELVRY03E1EDL32 {

    @XmlElement(name = "QUALI")
    protected String quali;
    @XmlElement(name = "KNOTE")
    protected String knote;
    @XmlElement(name = "ADRNR")
    protected String adrnr;
    @XmlElement(name = "VSTEL")
    protected String vstel;
    @XmlElement(name = "LSTEL")
    protected String lstel;
    @XmlElement(name = "WERKS")
    protected String werks;
    @XmlElement(name = "LGORT")
    protected String lgort;
    @XmlElement(name = "KUNNR")
    protected String kunnr;
    @XmlElement(name = "LIFNR")
    protected String lifnr;
    @XmlElement(name = "ABLAD")
    protected String ablad;
    @XmlElement(name = "LGNUM")
    protected String lgnum;
    @XmlElement(name = "LGTOR")
    protected String lgtor;
    @XmlElement(name = "E1EDL45")
    protected DELVRY03E1EDL45 e1EDL45;
    @XmlElement(name = "E1ADRM3")
    protected DELVRY03E1ADRM3 e1ADRM3;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the quali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALI() {
        return quali;
    }

    /**
     * Sets the value of the quali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALI(String value) {
        this.quali = value;
    }

    /**
     * Gets the value of the knote property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKNOTE() {
        return knote;
    }

    /**
     * Sets the value of the knote property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKNOTE(String value) {
        this.knote = value;
    }

    /**
     * Gets the value of the adrnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getADRNR() {
        return adrnr;
    }

    /**
     * Sets the value of the adrnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setADRNR(String value) {
        this.adrnr = value;
    }

    /**
     * Gets the value of the vstel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTEL() {
        return vstel;
    }

    /**
     * Sets the value of the vstel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTEL(String value) {
        this.vstel = value;
    }

    /**
     * Gets the value of the lstel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLSTEL() {
        return lstel;
    }

    /**
     * Sets the value of the lstel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLSTEL(String value) {
        this.lstel = value;
    }

    /**
     * Gets the value of the werks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWERKS() {
        return werks;
    }

    /**
     * Sets the value of the werks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWERKS(String value) {
        this.werks = value;
    }

    /**
     * Gets the value of the lgort property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGORT() {
        return lgort;
    }

    /**
     * Sets the value of the lgort property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGORT(String value) {
        this.lgort = value;
    }

    /**
     * Gets the value of the kunnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKUNNR() {
        return kunnr;
    }

    /**
     * Sets the value of the kunnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKUNNR(String value) {
        this.kunnr = value;
    }

    /**
     * Gets the value of the lifnr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIFNR() {
        return lifnr;
    }

    /**
     * Sets the value of the lifnr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIFNR(String value) {
        this.lifnr = value;
    }

    /**
     * Gets the value of the ablad property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getABLAD() {
        return ablad;
    }

    /**
     * Sets the value of the ablad property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setABLAD(String value) {
        this.ablad = value;
    }

    /**
     * Gets the value of the lgnum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGNUM() {
        return lgnum;
    }

    /**
     * Sets the value of the lgnum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGNUM(String value) {
        this.lgnum = value;
    }

    /**
     * Gets the value of the lgtor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGTOR() {
        return lgtor;
    }

    /**
     * Sets the value of the lgtor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGTOR(String value) {
        this.lgtor = value;
    }

    /**
     * Gets the value of the e1EDL45 property.
     * 
     * @return
     *     possible object is
     *     {@link DELVRY03E1EDL45 }
     *     
     */
    public DELVRY03E1EDL45 getE1EDL45() {
        return e1EDL45;
    }

    /**
     * Sets the value of the e1EDL45 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELVRY03E1EDL45 }
     *     
     */
    public void setE1EDL45(DELVRY03E1EDL45 value) {
        this.e1EDL45 = value;
    }

    /**
     * Gets the value of the e1ADRM3 property.
     * 
     * @return
     *     possible object is
     *     {@link DELVRY03E1ADRM3 }
     *     
     */
    public DELVRY03E1ADRM3 getE1ADRM3() {
        return e1ADRM3;
    }

    /**
     * Sets the value of the e1ADRM3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELVRY03E1ADRM3 }
     *     
     */
    public void setE1ADRM3(DELVRY03E1ADRM3 value) {
        this.e1ADRM3 = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
