//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.06.01 at 08:25:51 ÏÂÎç CST 
//


package com.faurecia.model.mbgmcr;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * BAPI Communication Structure: Create Material
 * 				Document Item
 * 
 * <p>Java class for MBGMCR02.E1BP2017_GM_ITEM_CREATE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MBGMCR02.E1BP2017_GM_ITEM_CREATE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MATERIAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PLANT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_LOC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BATCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STCK_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SPEC_STOCK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VENDOR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CUSTOMER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SALES_ORD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="S_ORD_ITEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SCHED_LINE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VAL_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ENTRY_QNT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ENTRY_UOM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ENTRY_UOM_ISO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PO_PR_QNT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDERPR_UN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDERPR_UN_ISO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PO_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PO_ITEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SHIPPING" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COMP_SHIP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NO_MORE_GR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ITEM_TEXT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GR_RCPT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UNLOAD_PT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COSTCENTER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDERID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ORDER_ITNO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CALC_MOTIVE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ASSET_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUB_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RESERV_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RES_ITEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RES_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WITHDRAWN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_MAT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_PLANT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_STLOC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_BATCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_VAL_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MVT_IND" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_REAS" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RL_EST_KEY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REF_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="COST_OBJ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROFIT_SEGM_NO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROFIT_CTR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="WBS_ELEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NETWORK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ACTIVITY" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PART_ACCT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AMOUNT_LC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AMOUNT_SV" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REF_DOC_YR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REF_DOC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="REF_DOC_IT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EXPIRYDATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PROD_DATE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FUND" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FUNDS_CTR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="16"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CMMT_ITEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="14"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VAL_SALES_ORD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VAL_S_ORD_ITEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VAL_WBS_ELEM" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="24"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GL_ACCOUNT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IND_PROPOSE_QUANX" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="XSTOB" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EAN_UPC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="18"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DELIV_NUMB_TO_SEARCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DELIV_ITEM_TO_SEARCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SERIALNO_AUTO_NUMBERASSIGNMENT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VENDRBATCH" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_TYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_BIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SU_PL_STCK_1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ST_UN_QTYY_1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ST_UN_QTYY_1_ISO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UNITTYPE_1" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SU_PL_STCK_2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ST_UN_QTYY_2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ST_UN_QTYY_2_ISO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="UNITTYPE_2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_TYPE_PC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_BIN_PC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NO_PST_CHGNT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GR_NUMBER" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_TYPE_ST" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="STGE_BIN_ST" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATDOC_TR_CANCEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATITEM_TR_CANCEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATYEAR_TR_CANCEL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NO_TRANSFER_REQ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CO_BUSPROC" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ACTTYPE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SUPPL_VEND" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATERIAL_EXTERNAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATERIAL_GUID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MATERIAL_VERSION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_MAT_EXTERNAL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_MAT_GUID" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="32"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MOVE_MAT_VERSION" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="FUNC_AREA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TR_PART_BA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PAR_COMPCO" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="E1BP2017_GM_ITEM_CREATE1" type="{}MBGMCR02.E1BP2017_GM_ITEM_CREATE1" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MBGMCR02.E1BP2017_GM_ITEM_CREATE", propOrder = {
    "material",
    "plant",
    "stgeloc",
    "batch",
    "movetype",
    "stcktype",
    "specstock",
    "vendor",
    "customer",
    "salesord",
    "sorditem",
    "schedline",
    "valtype",
    "entryqnt",
    "entryuom",
    "entryuomiso",
    "poprqnt",
    "orderprun",
    "orderpruniso",
    "ponumber",
    "poitem",
    "shipping",
    "compship",
    "nomoregr",
    "itemtext",
    "grrcpt",
    "unloadpt",
    "costcenter",
    "orderid",
    "orderitno",
    "calcmotive",
    "assetno",
    "subnumber",
    "reservno",
    "resitem",
    "restype",
    "withdrawn",
    "movemat",
    "moveplant",
    "movestloc",
    "movebatch",
    "movevaltype",
    "mvtind",
    "movereas",
    "rlestkey",
    "refdate",
    "costobj",
    "profitsegmno",
    "profitctr",
    "wbselem",
    "network",
    "activity",
    "partacct",
    "amountlc",
    "amountsv",
    "refdocyr",
    "refdoc",
    "refdocit",
    "expirydate",
    "proddate",
    "fund",
    "fundsctr",
    "cmmtitem",
    "valsalesord",
    "valsorditem",
    "valwbselem",
    "glaccount",
    "indproposequanx",
    "xstob",
    "eanupc",
    "delivnumbtosearch",
    "delivitemtosearch",
    "serialnoautonumberassignment",
    "vendrbatch",
    "stgetype",
    "stgebin",
    "suplstck1",
    "stunqtyy1",
    "stunqtyy1ISO",
    "unittype1",
    "suplstck2",
    "stunqtyy2",
    "stunqtyy2ISO",
    "unittype2",
    "stgetypepc",
    "stgebinpc",
    "nopstchgnt",
    "grnumber",
    "stgetypest",
    "stgebinst",
    "matdoctrcancel",
    "matitemtrcancel",
    "matyeartrcancel",
    "notransferreq",
    "cobusproc",
    "acttype",
    "supplvend",
    "materialexternal",
    "materialguid",
    "materialversion",
    "movematexternal",
    "movematguid",
    "movematversion",
    "funcarea",
    "trpartba",
    "parcompco",
    "e1BP2017GMITEMCREATE1"
})
public class MBGMCR02E1BP2017GMITEMCREATE {

    @XmlElement(name = "MATERIAL")
    protected String material;
    @XmlElement(name = "PLANT")
    protected String plant;
    @XmlElement(name = "STGE_LOC")
    protected String stgeloc;
    @XmlElement(name = "BATCH")
    protected String batch;
    @XmlElement(name = "MOVE_TYPE")
    protected String movetype;
    @XmlElement(name = "STCK_TYPE")
    protected String stcktype;
    @XmlElement(name = "SPEC_STOCK")
    protected String specstock;
    @XmlElement(name = "VENDOR")
    protected String vendor;
    @XmlElement(name = "CUSTOMER")
    protected String customer;
    @XmlElement(name = "SALES_ORD")
    protected String salesord;
    @XmlElement(name = "S_ORD_ITEM")
    protected String sorditem;
    @XmlElement(name = "SCHED_LINE")
    protected String schedline;
    @XmlElement(name = "VAL_TYPE")
    protected String valtype;
    @XmlElement(name = "ENTRY_QNT")
    protected String entryqnt;
    @XmlElement(name = "ENTRY_UOM")
    protected String entryuom;
    @XmlElement(name = "ENTRY_UOM_ISO")
    protected String entryuomiso;
    @XmlElement(name = "PO_PR_QNT")
    protected String poprqnt;
    @XmlElement(name = "ORDERPR_UN")
    protected String orderprun;
    @XmlElement(name = "ORDERPR_UN_ISO")
    protected String orderpruniso;
    @XmlElement(name = "PO_NUMBER")
    protected String ponumber;
    @XmlElement(name = "PO_ITEM")
    protected String poitem;
    @XmlElement(name = "SHIPPING")
    protected String shipping;
    @XmlElement(name = "COMP_SHIP")
    protected String compship;
    @XmlElement(name = "NO_MORE_GR")
    protected String nomoregr;
    @XmlElement(name = "ITEM_TEXT")
    protected String itemtext;
    @XmlElement(name = "GR_RCPT")
    protected String grrcpt;
    @XmlElement(name = "UNLOAD_PT")
    protected String unloadpt;
    @XmlElement(name = "COSTCENTER")
    protected String costcenter;
    @XmlElement(name = "ORDERID")
    protected String orderid;
    @XmlElement(name = "ORDER_ITNO")
    protected String orderitno;
    @XmlElement(name = "CALC_MOTIVE")
    protected String calcmotive;
    @XmlElement(name = "ASSET_NO")
    protected String assetno;
    @XmlElement(name = "SUB_NUMBER")
    protected String subnumber;
    @XmlElement(name = "RESERV_NO")
    protected String reservno;
    @XmlElement(name = "RES_ITEM")
    protected String resitem;
    @XmlElement(name = "RES_TYPE")
    protected String restype;
    @XmlElement(name = "WITHDRAWN")
    protected String withdrawn;
    @XmlElement(name = "MOVE_MAT")
    protected String movemat;
    @XmlElement(name = "MOVE_PLANT")
    protected String moveplant;
    @XmlElement(name = "MOVE_STLOC")
    protected String movestloc;
    @XmlElement(name = "MOVE_BATCH")
    protected String movebatch;
    @XmlElement(name = "MOVE_VAL_TYPE")
    protected String movevaltype;
    @XmlElement(name = "MVT_IND")
    protected String mvtind;
    @XmlElement(name = "MOVE_REAS")
    protected String movereas;
    @XmlElement(name = "RL_EST_KEY")
    protected String rlestkey;
    @XmlElement(name = "REF_DATE")
    protected String refdate;
    @XmlElement(name = "COST_OBJ")
    protected String costobj;
    @XmlElement(name = "PROFIT_SEGM_NO")
    protected String profitsegmno;
    @XmlElement(name = "PROFIT_CTR")
    protected String profitctr;
    @XmlElement(name = "WBS_ELEM")
    protected String wbselem;
    @XmlElement(name = "NETWORK")
    protected String network;
    @XmlElement(name = "ACTIVITY")
    protected String activity;
    @XmlElement(name = "PART_ACCT")
    protected String partacct;
    @XmlElement(name = "AMOUNT_LC")
    protected String amountlc;
    @XmlElement(name = "AMOUNT_SV")
    protected String amountsv;
    @XmlElement(name = "REF_DOC_YR")
    protected String refdocyr;
    @XmlElement(name = "REF_DOC")
    protected String refdoc;
    @XmlElement(name = "REF_DOC_IT")
    protected String refdocit;
    @XmlElement(name = "EXPIRYDATE")
    protected String expirydate;
    @XmlElement(name = "PROD_DATE")
    protected String proddate;
    @XmlElement(name = "FUND")
    protected String fund;
    @XmlElement(name = "FUNDS_CTR")
    protected String fundsctr;
    @XmlElement(name = "CMMT_ITEM")
    protected String cmmtitem;
    @XmlElement(name = "VAL_SALES_ORD")
    protected String valsalesord;
    @XmlElement(name = "VAL_S_ORD_ITEM")
    protected String valsorditem;
    @XmlElement(name = "VAL_WBS_ELEM")
    protected String valwbselem;
    @XmlElement(name = "GL_ACCOUNT")
    protected String glaccount;
    @XmlElement(name = "IND_PROPOSE_QUANX")
    protected String indproposequanx;
    @XmlElement(name = "XSTOB")
    protected String xstob;
    @XmlElement(name = "EAN_UPC")
    protected String eanupc;
    @XmlElement(name = "DELIV_NUMB_TO_SEARCH")
    protected String delivnumbtosearch;
    @XmlElement(name = "DELIV_ITEM_TO_SEARCH")
    protected String delivitemtosearch;
    @XmlElement(name = "SERIALNO_AUTO_NUMBERASSIGNMENT")
    protected String serialnoautonumberassignment;
    @XmlElement(name = "VENDRBATCH")
    protected String vendrbatch;
    @XmlElement(name = "STGE_TYPE")
    protected String stgetype;
    @XmlElement(name = "STGE_BIN")
    protected String stgebin;
    @XmlElement(name = "SU_PL_STCK_1")
    protected String suplstck1;
    @XmlElement(name = "ST_UN_QTYY_1")
    protected String stunqtyy1;
    @XmlElement(name = "ST_UN_QTYY_1_ISO")
    protected String stunqtyy1ISO;
    @XmlElement(name = "UNITTYPE_1")
    protected String unittype1;
    @XmlElement(name = "SU_PL_STCK_2")
    protected String suplstck2;
    @XmlElement(name = "ST_UN_QTYY_2")
    protected String stunqtyy2;
    @XmlElement(name = "ST_UN_QTYY_2_ISO")
    protected String stunqtyy2ISO;
    @XmlElement(name = "UNITTYPE_2")
    protected String unittype2;
    @XmlElement(name = "STGE_TYPE_PC")
    protected String stgetypepc;
    @XmlElement(name = "STGE_BIN_PC")
    protected String stgebinpc;
    @XmlElement(name = "NO_PST_CHGNT")
    protected String nopstchgnt;
    @XmlElement(name = "GR_NUMBER")
    protected String grnumber;
    @XmlElement(name = "STGE_TYPE_ST")
    protected String stgetypest;
    @XmlElement(name = "STGE_BIN_ST")
    protected String stgebinst;
    @XmlElement(name = "MATDOC_TR_CANCEL")
    protected String matdoctrcancel;
    @XmlElement(name = "MATITEM_TR_CANCEL")
    protected String matitemtrcancel;
    @XmlElement(name = "MATYEAR_TR_CANCEL")
    protected String matyeartrcancel;
    @XmlElement(name = "NO_TRANSFER_REQ")
    protected String notransferreq;
    @XmlElement(name = "CO_BUSPROC")
    protected String cobusproc;
    @XmlElement(name = "ACTTYPE")
    protected String acttype;
    @XmlElement(name = "SUPPL_VEND")
    protected String supplvend;
    @XmlElement(name = "MATERIAL_EXTERNAL")
    protected String materialexternal;
    @XmlElement(name = "MATERIAL_GUID")
    protected String materialguid;
    @XmlElement(name = "MATERIAL_VERSION")
    protected String materialversion;
    @XmlElement(name = "MOVE_MAT_EXTERNAL")
    protected String movematexternal;
    @XmlElement(name = "MOVE_MAT_GUID")
    protected String movematguid;
    @XmlElement(name = "MOVE_MAT_VERSION")
    protected String movematversion;
    @XmlElement(name = "FUNC_AREA")
    protected String funcarea;
    @XmlElement(name = "TR_PART_BA")
    protected String trpartba;
    @XmlElement(name = "PAR_COMPCO")
    protected String parcompco;
    @XmlElement(name = "E1BP2017_GM_ITEM_CREATE1")
    protected MBGMCR02E1BP2017GMITEMCREATE1 e1BP2017GMITEMCREATE1;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the material property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIAL() {
        return material;
    }

    /**
     * Sets the value of the material property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIAL(String value) {
        this.material = value;
    }

    /**
     * Gets the value of the plant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPLANT() {
        return plant;
    }

    /**
     * Sets the value of the plant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPLANT(String value) {
        this.plant = value;
    }

    /**
     * Gets the value of the stgeloc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGELOC() {
        return stgeloc;
    }

    /**
     * Sets the value of the stgeloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGELOC(String value) {
        this.stgeloc = value;
    }

    /**
     * Gets the value of the batch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBATCH() {
        return batch;
    }

    /**
     * Sets the value of the batch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBATCH(String value) {
        this.batch = value;
    }

    /**
     * Gets the value of the movetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVETYPE() {
        return movetype;
    }

    /**
     * Sets the value of the movetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVETYPE(String value) {
        this.movetype = value;
    }

    /**
     * Gets the value of the stcktype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTCKTYPE() {
        return stcktype;
    }

    /**
     * Sets the value of the stcktype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTCKTYPE(String value) {
        this.stcktype = value;
    }

    /**
     * Gets the value of the specstock property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSPECSTOCK() {
        return specstock;
    }

    /**
     * Sets the value of the specstock property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSPECSTOCK(String value) {
        this.specstock = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVENDOR() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVENDOR(String value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the customer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCUSTOMER() {
        return customer;
    }

    /**
     * Sets the value of the customer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCUSTOMER(String value) {
        this.customer = value;
    }

    /**
     * Gets the value of the salesord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSALESORD() {
        return salesord;
    }

    /**
     * Sets the value of the salesord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSALESORD(String value) {
        this.salesord = value;
    }

    /**
     * Gets the value of the sorditem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSORDITEM() {
        return sorditem;
    }

    /**
     * Sets the value of the sorditem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSORDITEM(String value) {
        this.sorditem = value;
    }

    /**
     * Gets the value of the schedline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSCHEDLINE() {
        return schedline;
    }

    /**
     * Sets the value of the schedline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSCHEDLINE(String value) {
        this.schedline = value;
    }

    /**
     * Gets the value of the valtype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALTYPE() {
        return valtype;
    }

    /**
     * Sets the value of the valtype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALTYPE(String value) {
        this.valtype = value;
    }

    /**
     * Gets the value of the entryqnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTRYQNT() {
        return entryqnt;
    }

    /**
     * Sets the value of the entryqnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTRYQNT(String value) {
        this.entryqnt = value;
    }

    /**
     * Gets the value of the entryuom property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTRYUOM() {
        return entryuom;
    }

    /**
     * Sets the value of the entryuom property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTRYUOM(String value) {
        this.entryuom = value;
    }

    /**
     * Gets the value of the entryuomiso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getENTRYUOMISO() {
        return entryuomiso;
    }

    /**
     * Sets the value of the entryuomiso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setENTRYUOMISO(String value) {
        this.entryuomiso = value;
    }

    /**
     * Gets the value of the poprqnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOPRQNT() {
        return poprqnt;
    }

    /**
     * Sets the value of the poprqnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOPRQNT(String value) {
        this.poprqnt = value;
    }

    /**
     * Gets the value of the orderprun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERPRUN() {
        return orderprun;
    }

    /**
     * Sets the value of the orderprun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERPRUN(String value) {
        this.orderprun = value;
    }

    /**
     * Gets the value of the orderpruniso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERPRUNISO() {
        return orderpruniso;
    }

    /**
     * Sets the value of the orderpruniso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERPRUNISO(String value) {
        this.orderpruniso = value;
    }

    /**
     * Gets the value of the ponumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPONUMBER() {
        return ponumber;
    }

    /**
     * Sets the value of the ponumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPONUMBER(String value) {
        this.ponumber = value;
    }

    /**
     * Gets the value of the poitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPOITEM() {
        return poitem;
    }

    /**
     * Sets the value of the poitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPOITEM(String value) {
        this.poitem = value;
    }

    /**
     * Gets the value of the shipping property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSHIPPING() {
        return shipping;
    }

    /**
     * Sets the value of the shipping property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSHIPPING(String value) {
        this.shipping = value;
    }

    /**
     * Gets the value of the compship property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOMPSHIP() {
        return compship;
    }

    /**
     * Sets the value of the compship property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOMPSHIP(String value) {
        this.compship = value;
    }

    /**
     * Gets the value of the nomoregr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOMOREGR() {
        return nomoregr;
    }

    /**
     * Sets the value of the nomoregr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOMOREGR(String value) {
        this.nomoregr = value;
    }

    /**
     * Gets the value of the itemtext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getITEMTEXT() {
        return itemtext;
    }

    /**
     * Sets the value of the itemtext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setITEMTEXT(String value) {
        this.itemtext = value;
    }

    /**
     * Gets the value of the grrcpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGRRCPT() {
        return grrcpt;
    }

    /**
     * Sets the value of the grrcpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGRRCPT(String value) {
        this.grrcpt = value;
    }

    /**
     * Gets the value of the unloadpt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNLOADPT() {
        return unloadpt;
    }

    /**
     * Sets the value of the unloadpt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNLOADPT(String value) {
        this.unloadpt = value;
    }

    /**
     * Gets the value of the costcenter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSTCENTER() {
        return costcenter;
    }

    /**
     * Sets the value of the costcenter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSTCENTER(String value) {
        this.costcenter = value;
    }

    /**
     * Gets the value of the orderid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERID() {
        return orderid;
    }

    /**
     * Sets the value of the orderid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERID(String value) {
        this.orderid = value;
    }

    /**
     * Gets the value of the orderitno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getORDERITNO() {
        return orderitno;
    }

    /**
     * Sets the value of the orderitno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setORDERITNO(String value) {
        this.orderitno = value;
    }

    /**
     * Gets the value of the calcmotive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCALCMOTIVE() {
        return calcmotive;
    }

    /**
     * Sets the value of the calcmotive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCALCMOTIVE(String value) {
        this.calcmotive = value;
    }

    /**
     * Gets the value of the assetno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getASSETNO() {
        return assetno;
    }

    /**
     * Sets the value of the assetno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setASSETNO(String value) {
        this.assetno = value;
    }

    /**
     * Gets the value of the subnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUBNUMBER() {
        return subnumber;
    }

    /**
     * Sets the value of the subnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUBNUMBER(String value) {
        this.subnumber = value;
    }

    /**
     * Gets the value of the reservno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESERVNO() {
        return reservno;
    }

    /**
     * Sets the value of the reservno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESERVNO(String value) {
        this.reservno = value;
    }

    /**
     * Gets the value of the resitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESITEM() {
        return resitem;
    }

    /**
     * Sets the value of the resitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESITEM(String value) {
        this.resitem = value;
    }

    /**
     * Gets the value of the restype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRESTYPE() {
        return restype;
    }

    /**
     * Sets the value of the restype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRESTYPE(String value) {
        this.restype = value;
    }

    /**
     * Gets the value of the withdrawn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWITHDRAWN() {
        return withdrawn;
    }

    /**
     * Sets the value of the withdrawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWITHDRAWN(String value) {
        this.withdrawn = value;
    }

    /**
     * Gets the value of the movemat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEMAT() {
        return movemat;
    }

    /**
     * Sets the value of the movemat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEMAT(String value) {
        this.movemat = value;
    }

    /**
     * Gets the value of the moveplant property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEPLANT() {
        return moveplant;
    }

    /**
     * Sets the value of the moveplant property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEPLANT(String value) {
        this.moveplant = value;
    }

    /**
     * Gets the value of the movestloc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVESTLOC() {
        return movestloc;
    }

    /**
     * Sets the value of the movestloc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVESTLOC(String value) {
        this.movestloc = value;
    }

    /**
     * Gets the value of the movebatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEBATCH() {
        return movebatch;
    }

    /**
     * Sets the value of the movebatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEBATCH(String value) {
        this.movebatch = value;
    }

    /**
     * Gets the value of the movevaltype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEVALTYPE() {
        return movevaltype;
    }

    /**
     * Sets the value of the movevaltype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEVALTYPE(String value) {
        this.movevaltype = value;
    }

    /**
     * Gets the value of the mvtind property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMVTIND() {
        return mvtind;
    }

    /**
     * Sets the value of the mvtind property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMVTIND(String value) {
        this.mvtind = value;
    }

    /**
     * Gets the value of the movereas property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEREAS() {
        return movereas;
    }

    /**
     * Sets the value of the movereas property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEREAS(String value) {
        this.movereas = value;
    }

    /**
     * Gets the value of the rlestkey property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRLESTKEY() {
        return rlestkey;
    }

    /**
     * Sets the value of the rlestkey property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRLESTKEY(String value) {
        this.rlestkey = value;
    }

    /**
     * Gets the value of the refdate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDATE() {
        return refdate;
    }

    /**
     * Sets the value of the refdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDATE(String value) {
        this.refdate = value;
    }

    /**
     * Gets the value of the costobj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOSTOBJ() {
        return costobj;
    }

    /**
     * Sets the value of the costobj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOSTOBJ(String value) {
        this.costobj = value;
    }

    /**
     * Gets the value of the profitsegmno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROFITSEGMNO() {
        return profitsegmno;
    }

    /**
     * Sets the value of the profitsegmno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROFITSEGMNO(String value) {
        this.profitsegmno = value;
    }

    /**
     * Gets the value of the profitctr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPROFITCTR() {
        return profitctr;
    }

    /**
     * Sets the value of the profitctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPROFITCTR(String value) {
        this.profitctr = value;
    }

    /**
     * Gets the value of the wbselem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWBSELEM() {
        return wbselem;
    }

    /**
     * Sets the value of the wbselem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWBSELEM(String value) {
        this.wbselem = value;
    }

    /**
     * Gets the value of the network property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNETWORK() {
        return network;
    }

    /**
     * Sets the value of the network property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNETWORK(String value) {
        this.network = value;
    }

    /**
     * Gets the value of the activity property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTIVITY() {
        return activity;
    }

    /**
     * Sets the value of the activity property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTIVITY(String value) {
        this.activity = value;
    }

    /**
     * Gets the value of the partacct property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARTACCT() {
        return partacct;
    }

    /**
     * Sets the value of the partacct property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARTACCT(String value) {
        this.partacct = value;
    }

    /**
     * Gets the value of the amountlc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNTLC() {
        return amountlc;
    }

    /**
     * Sets the value of the amountlc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNTLC(String value) {
        this.amountlc = value;
    }

    /**
     * Gets the value of the amountsv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAMOUNTSV() {
        return amountsv;
    }

    /**
     * Sets the value of the amountsv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAMOUNTSV(String value) {
        this.amountsv = value;
    }

    /**
     * Gets the value of the refdocyr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDOCYR() {
        return refdocyr;
    }

    /**
     * Sets the value of the refdocyr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDOCYR(String value) {
        this.refdocyr = value;
    }

    /**
     * Gets the value of the refdoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDOC() {
        return refdoc;
    }

    /**
     * Sets the value of the refdoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDOC(String value) {
        this.refdoc = value;
    }

    /**
     * Gets the value of the refdocit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getREFDOCIT() {
        return refdocit;
    }

    /**
     * Sets the value of the refdocit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setREFDOCIT(String value) {
        this.refdocit = value;
    }

    /**
     * Gets the value of the expirydate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPIRYDATE() {
        return expirydate;
    }

    /**
     * Sets the value of the expirydate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPIRYDATE(String value) {
        this.expirydate = value;
    }

    /**
     * Gets the value of the proddate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPRODDATE() {
        return proddate;
    }

    /**
     * Sets the value of the proddate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPRODDATE(String value) {
        this.proddate = value;
    }

    /**
     * Gets the value of the fund property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUND() {
        return fund;
    }

    /**
     * Sets the value of the fund property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUND(String value) {
        this.fund = value;
    }

    /**
     * Gets the value of the fundsctr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUNDSCTR() {
        return fundsctr;
    }

    /**
     * Sets the value of the fundsctr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUNDSCTR(String value) {
        this.fundsctr = value;
    }

    /**
     * Gets the value of the cmmtitem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCMMTITEM() {
        return cmmtitem;
    }

    /**
     * Sets the value of the cmmtitem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCMMTITEM(String value) {
        this.cmmtitem = value;
    }

    /**
     * Gets the value of the valsalesord property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALSALESORD() {
        return valsalesord;
    }

    /**
     * Sets the value of the valsalesord property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALSALESORD(String value) {
        this.valsalesord = value;
    }

    /**
     * Gets the value of the valsorditem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALSORDITEM() {
        return valsorditem;
    }

    /**
     * Sets the value of the valsorditem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALSORDITEM(String value) {
        this.valsorditem = value;
    }

    /**
     * Gets the value of the valwbselem property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVALWBSELEM() {
        return valwbselem;
    }

    /**
     * Sets the value of the valwbselem property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVALWBSELEM(String value) {
        this.valwbselem = value;
    }

    /**
     * Gets the value of the glaccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGLACCOUNT() {
        return glaccount;
    }

    /**
     * Sets the value of the glaccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGLACCOUNT(String value) {
        this.glaccount = value;
    }

    /**
     * Gets the value of the indproposequanx property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINDPROPOSEQUANX() {
        return indproposequanx;
    }

    /**
     * Sets the value of the indproposequanx property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINDPROPOSEQUANX(String value) {
        this.indproposequanx = value;
    }

    /**
     * Gets the value of the xstob property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXSTOB() {
        return xstob;
    }

    /**
     * Sets the value of the xstob property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXSTOB(String value) {
        this.xstob = value;
    }

    /**
     * Gets the value of the eanupc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEANUPC() {
        return eanupc;
    }

    /**
     * Sets the value of the eanupc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEANUPC(String value) {
        this.eanupc = value;
    }

    /**
     * Gets the value of the delivnumbtosearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVNUMBTOSEARCH() {
        return delivnumbtosearch;
    }

    /**
     * Sets the value of the delivnumbtosearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVNUMBTOSEARCH(String value) {
        this.delivnumbtosearch = value;
    }

    /**
     * Gets the value of the delivitemtosearch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDELIVITEMTOSEARCH() {
        return delivitemtosearch;
    }

    /**
     * Sets the value of the delivitemtosearch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDELIVITEMTOSEARCH(String value) {
        this.delivitemtosearch = value;
    }

    /**
     * Gets the value of the serialnoautonumberassignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSERIALNOAUTONUMBERASSIGNMENT() {
        return serialnoautonumberassignment;
    }

    /**
     * Sets the value of the serialnoautonumberassignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSERIALNOAUTONUMBERASSIGNMENT(String value) {
        this.serialnoautonumberassignment = value;
    }

    /**
     * Gets the value of the vendrbatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVENDRBATCH() {
        return vendrbatch;
    }

    /**
     * Sets the value of the vendrbatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVENDRBATCH(String value) {
        this.vendrbatch = value;
    }

    /**
     * Gets the value of the stgetype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGETYPE() {
        return stgetype;
    }

    /**
     * Sets the value of the stgetype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGETYPE(String value) {
        this.stgetype = value;
    }

    /**
     * Gets the value of the stgebin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGEBIN() {
        return stgebin;
    }

    /**
     * Sets the value of the stgebin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGEBIN(String value) {
        this.stgebin = value;
    }

    /**
     * Gets the value of the suplstck1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPLSTCK1() {
        return suplstck1;
    }

    /**
     * Sets the value of the suplstck1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPLSTCK1(String value) {
        this.suplstck1 = value;
    }

    /**
     * Gets the value of the stunqtyy1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUNQTYY1() {
        return stunqtyy1;
    }

    /**
     * Sets the value of the stunqtyy1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUNQTYY1(String value) {
        this.stunqtyy1 = value;
    }

    /**
     * Gets the value of the stunqtyy1ISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUNQTYY1ISO() {
        return stunqtyy1ISO;
    }

    /**
     * Sets the value of the stunqtyy1ISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUNQTYY1ISO(String value) {
        this.stunqtyy1ISO = value;
    }

    /**
     * Gets the value of the unittype1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITTYPE1() {
        return unittype1;
    }

    /**
     * Sets the value of the unittype1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITTYPE1(String value) {
        this.unittype1 = value;
    }

    /**
     * Gets the value of the suplstck2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPLSTCK2() {
        return suplstck2;
    }

    /**
     * Sets the value of the suplstck2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPLSTCK2(String value) {
        this.suplstck2 = value;
    }

    /**
     * Gets the value of the stunqtyy2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUNQTYY2() {
        return stunqtyy2;
    }

    /**
     * Sets the value of the stunqtyy2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUNQTYY2(String value) {
        this.stunqtyy2 = value;
    }

    /**
     * Gets the value of the stunqtyy2ISO property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTUNQTYY2ISO() {
        return stunqtyy2ISO;
    }

    /**
     * Sets the value of the stunqtyy2ISO property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTUNQTYY2ISO(String value) {
        this.stunqtyy2ISO = value;
    }

    /**
     * Gets the value of the unittype2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNITTYPE2() {
        return unittype2;
    }

    /**
     * Sets the value of the unittype2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNITTYPE2(String value) {
        this.unittype2 = value;
    }

    /**
     * Gets the value of the stgetypepc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGETYPEPC() {
        return stgetypepc;
    }

    /**
     * Sets the value of the stgetypepc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGETYPEPC(String value) {
        this.stgetypepc = value;
    }

    /**
     * Gets the value of the stgebinpc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGEBINPC() {
        return stgebinpc;
    }

    /**
     * Sets the value of the stgebinpc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGEBINPC(String value) {
        this.stgebinpc = value;
    }

    /**
     * Gets the value of the nopstchgnt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOPSTCHGNT() {
        return nopstchgnt;
    }

    /**
     * Sets the value of the nopstchgnt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOPSTCHGNT(String value) {
        this.nopstchgnt = value;
    }

    /**
     * Gets the value of the grnumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGRNUMBER() {
        return grnumber;
    }

    /**
     * Sets the value of the grnumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGRNUMBER(String value) {
        this.grnumber = value;
    }

    /**
     * Gets the value of the stgetypest property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGETYPEST() {
        return stgetypest;
    }

    /**
     * Sets the value of the stgetypest property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGETYPEST(String value) {
        this.stgetypest = value;
    }

    /**
     * Gets the value of the stgebinst property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTGEBINST() {
        return stgebinst;
    }

    /**
     * Sets the value of the stgebinst property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTGEBINST(String value) {
        this.stgebinst = value;
    }

    /**
     * Gets the value of the matdoctrcancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATDOCTRCANCEL() {
        return matdoctrcancel;
    }

    /**
     * Sets the value of the matdoctrcancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATDOCTRCANCEL(String value) {
        this.matdoctrcancel = value;
    }

    /**
     * Gets the value of the matitemtrcancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATITEMTRCANCEL() {
        return matitemtrcancel;
    }

    /**
     * Sets the value of the matitemtrcancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATITEMTRCANCEL(String value) {
        this.matitemtrcancel = value;
    }

    /**
     * Gets the value of the matyeartrcancel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATYEARTRCANCEL() {
        return matyeartrcancel;
    }

    /**
     * Sets the value of the matyeartrcancel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATYEARTRCANCEL(String value) {
        this.matyeartrcancel = value;
    }

    /**
     * Gets the value of the notransferreq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNOTRANSFERREQ() {
        return notransferreq;
    }

    /**
     * Sets the value of the notransferreq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNOTRANSFERREQ(String value) {
        this.notransferreq = value;
    }

    /**
     * Gets the value of the cobusproc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCOBUSPROC() {
        return cobusproc;
    }

    /**
     * Sets the value of the cobusproc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCOBUSPROC(String value) {
        this.cobusproc = value;
    }

    /**
     * Gets the value of the acttype property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACTTYPE() {
        return acttype;
    }

    /**
     * Sets the value of the acttype property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACTTYPE(String value) {
        this.acttype = value;
    }

    /**
     * Gets the value of the supplvend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSUPPLVEND() {
        return supplvend;
    }

    /**
     * Sets the value of the supplvend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSUPPLVEND(String value) {
        this.supplvend = value;
    }

    /**
     * Gets the value of the materialexternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIALEXTERNAL() {
        return materialexternal;
    }

    /**
     * Sets the value of the materialexternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIALEXTERNAL(String value) {
        this.materialexternal = value;
    }

    /**
     * Gets the value of the materialguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIALGUID() {
        return materialguid;
    }

    /**
     * Sets the value of the materialguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIALGUID(String value) {
        this.materialguid = value;
    }

    /**
     * Gets the value of the materialversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMATERIALVERSION() {
        return materialversion;
    }

    /**
     * Sets the value of the materialversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMATERIALVERSION(String value) {
        this.materialversion = value;
    }

    /**
     * Gets the value of the movematexternal property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEMATEXTERNAL() {
        return movematexternal;
    }

    /**
     * Sets the value of the movematexternal property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEMATEXTERNAL(String value) {
        this.movematexternal = value;
    }

    /**
     * Gets the value of the movematguid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEMATGUID() {
        return movematguid;
    }

    /**
     * Sets the value of the movematguid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEMATGUID(String value) {
        this.movematguid = value;
    }

    /**
     * Gets the value of the movematversion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMOVEMATVERSION() {
        return movematversion;
    }

    /**
     * Sets the value of the movematversion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMOVEMATVERSION(String value) {
        this.movematversion = value;
    }

    /**
     * Gets the value of the funcarea property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFUNCAREA() {
        return funcarea;
    }

    /**
     * Sets the value of the funcarea property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFUNCAREA(String value) {
        this.funcarea = value;
    }

    /**
     * Gets the value of the trpartba property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRPARTBA() {
        return trpartba;
    }

    /**
     * Sets the value of the trpartba property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRPARTBA(String value) {
        this.trpartba = value;
    }

    /**
     * Gets the value of the parcompco property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPARCOMPCO() {
        return parcompco;
    }

    /**
     * Sets the value of the parcompco property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPARCOMPCO(String value) {
        this.parcompco = value;
    }

    /**
     * Gets the value of the e1BP2017GMITEMCREATE1 property.
     * 
     * @return
     *     possible object is
     *     {@link MBGMCR02E1BP2017GMITEMCREATE1 }
     *     
     */
    public MBGMCR02E1BP2017GMITEMCREATE1 getE1BP2017GMITEMCREATE1() {
        return e1BP2017GMITEMCREATE1;
    }

    /**
     * Sets the value of the e1BP2017GMITEMCREATE1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link MBGMCR02E1BP2017GMITEMCREATE1 }
     *     
     */
    public void setE1BP2017GMITEMCREATE1(MBGMCR02E1BP2017GMITEMCREATE1 value) {
        this.e1BP2017GMITEMCREATE1 = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
