//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:48 ÏÂÎç CST 
//


package com.faurecia.model.delfor;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * IDoc: Packing Data FRC/JIT Component Supplier
 * 
 * <p>Java class for DELFOR02.E1EDP14 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELFOR02.E1EDP14">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="PCKAR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PCKNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="35"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ANZPK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PCKSL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ANZAR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MAZAR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MMPCK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MGPCK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VPACK" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="11"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GDATV" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELFOR02.E1EDP14", propOrder = {
    "pckar",
    "pcknr",
    "anzpk",
    "pcksl",
    "anzar",
    "mazar",
    "mmpck",
    "lpack",
    "bpack",
    "hpack",
    "mgpck",
    "gpack",
    "npack",
    "vpack",
    "gdatv"
})
public class DELFOR02E1EDP14 {

    @XmlElement(name = "PCKAR")
    protected String pckar;
    @XmlElement(name = "PCKNR")
    protected String pcknr;
    @XmlElement(name = "ANZPK")
    protected String anzpk;
    @XmlElement(name = "PCKSL")
    protected String pcksl;
    @XmlElement(name = "ANZAR")
    protected String anzar;
    @XmlElement(name = "MAZAR")
    protected String mazar;
    @XmlElement(name = "MMPCK")
    protected String mmpck;
    @XmlElement(name = "LPACK")
    protected String lpack;
    @XmlElement(name = "BPACK")
    protected String bpack;
    @XmlElement(name = "HPACK")
    protected String hpack;
    @XmlElement(name = "MGPCK")
    protected String mgpck;
    @XmlElement(name = "GPACK")
    protected String gpack;
    @XmlElement(name = "NPACK")
    protected String npack;
    @XmlElement(name = "VPACK")
    protected String vpack;
    @XmlElement(name = "GDATV")
    protected String gdatv;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the pckar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCKAR() {
        return pckar;
    }

    /**
     * Sets the value of the pckar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCKAR(String value) {
        this.pckar = value;
    }

    /**
     * Gets the value of the pcknr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCKNR() {
        return pcknr;
    }

    /**
     * Sets the value of the pcknr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCKNR(String value) {
        this.pcknr = value;
    }

    /**
     * Gets the value of the anzpk property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANZPK() {
        return anzpk;
    }

    /**
     * Sets the value of the anzpk property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANZPK(String value) {
        this.anzpk = value;
    }

    /**
     * Gets the value of the pcksl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPCKSL() {
        return pcksl;
    }

    /**
     * Sets the value of the pcksl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPCKSL(String value) {
        this.pcksl = value;
    }

    /**
     * Gets the value of the anzar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getANZAR() {
        return anzar;
    }

    /**
     * Sets the value of the anzar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setANZAR(String value) {
        this.anzar = value;
    }

    /**
     * Gets the value of the mazar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMAZAR() {
        return mazar;
    }

    /**
     * Sets the value of the mazar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMAZAR(String value) {
        this.mazar = value;
    }

    /**
     * Gets the value of the mmpck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMMPCK() {
        return mmpck;
    }

    /**
     * Sets the value of the mmpck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMMPCK(String value) {
        this.mmpck = value;
    }

    /**
     * Gets the value of the lpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLPACK() {
        return lpack;
    }

    /**
     * Sets the value of the lpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLPACK(String value) {
        this.lpack = value;
    }

    /**
     * Gets the value of the bpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBPACK() {
        return bpack;
    }

    /**
     * Sets the value of the bpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBPACK(String value) {
        this.bpack = value;
    }

    /**
     * Gets the value of the hpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHPACK() {
        return hpack;
    }

    /**
     * Sets the value of the hpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHPACK(String value) {
        this.hpack = value;
    }

    /**
     * Gets the value of the mgpck property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMGPCK() {
        return mgpck;
    }

    /**
     * Sets the value of the mgpck property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMGPCK(String value) {
        this.mgpck = value;
    }

    /**
     * Gets the value of the gpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGPACK() {
        return gpack;
    }

    /**
     * Sets the value of the gpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGPACK(String value) {
        this.gpack = value;
    }

    /**
     * Gets the value of the npack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNPACK() {
        return npack;
    }

    /**
     * Sets the value of the npack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNPACK(String value) {
        this.npack = value;
    }

    /**
     * Gets the value of the vpack property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVPACK() {
        return vpack;
    }

    /**
     * Sets the value of the vpack property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVPACK(String value) {
        this.vpack = value;
    }

    /**
     * Gets the value of the gdatv property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGDATV() {
        return gdatv;
    }

    /**
     * Sets the value of the gdatv property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGDATV(String value) {
        this.gdatv = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
