//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.CompactFramework.Design.Data 2.0.50727.3615 版自动生成。
// 
namespace SmartDevice.SmartDeviceWS {
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SmartDeviceMgrWSSoap", Namespace="http://com.LocalSystem.Webservice")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityBase))]
    public partial class SmartDeviceMgrWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SmartDeviceMgrWS() {
            this.Url = "http://192.168.11.4:8081/LocalSystem/Webservice/SmartDeviceMgrWS.asmx";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.LocalSystem.Webservice/LoadAppUser", RequestNamespace="http://com.LocalSystem.Webservice", ResponseNamespace="http://com.LocalSystem.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public AppUser LoadAppUser(string userCode) {
            object[] results = this.Invoke("LoadAppUser", new object[] {
                        userCode});
            return ((AppUser)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginLoadAppUser(string userCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("LoadAppUser", new object[] {
                        userCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public AppUser EndLoadAppUser(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AppUser)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.LocalSystem.Webservice/CheckAndLoadBarCode", RequestNamespace="http://com.LocalSystem.Webservice", ResponseNamespace="http://com.LocalSystem.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public BarCode CheckAndLoadBarCode(string barCode, string userCode) {
            object[] results = this.Invoke("CheckAndLoadBarCode", new object[] {
                        barCode,
                        userCode});
            return ((BarCode)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCheckAndLoadBarCode(string barCode, string userCode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CheckAndLoadBarCode", new object[] {
                        barCode,
                        userCode}, callback, asyncState);
        }
        
        /// <remarks/>
        public BarCode EndCheckAndLoadBarCode(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((BarCode)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://com.LocalSystem.Webservice/CreateBarCode", RequestNamespace="http://com.LocalSystem.Webservice", ResponseNamespace="http://com.LocalSystem.Webservice", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CreateBarCode(BarCode[] barCodes, string createUser) {
            this.Invoke("CreateBarCode", new object[] {
                        barCodes,
                        createUser});
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginCreateBarCode(BarCode[] barCodes, string createUser, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("CreateBarCode", new object[] {
                        barCodes,
                        createUser}, callback, asyncState);
        }
        
        /// <remarks/>
        public void EndCreateBarCode(System.IAsyncResult asyncResult) {
            this.EndInvoke(asyncResult);
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.LocalSystem.Webservice")]
    public partial class AppUser : AppUserBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AppUser))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.LocalSystem.Webservice")]
    public abstract partial class AppUserBase : EntityBase {
        
        private string codeField;
        
        private string addressField;
        
        private string emailField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string passwordField;
        
        private string phoneField;
        
        private string faxField;
        
        private string languageField;
        
        private bool isActiveField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public string Fax {
            get {
                return this.faxField;
            }
            set {
                this.faxField = value;
            }
        }
        
        /// <remarks/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        public bool IsActive {
            get {
                return this.isActiveField;
            }
            set {
                this.isActiveField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BarCodeBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BarCode))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AppUserBase))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AppUser))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.LocalSystem.Webservice")]
    public abstract partial class EntityBase {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BarCode))]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.LocalSystem.Webservice")]
    public abstract partial class BarCodeBase : EntityBase {
        
        private int idField;
        
        private System.Nullable<int> seqField;
        
        private string barCodeField;
        
        private string lotNoField;
        
        private string itemCodeField;
        
        private string itemDescriptionField;
        
        private string uomField;
        
        private System.Nullable<decimal> ucField;
        
        private decimal qtyField;
        
        private string statusField;
        
        private string supplierCodeField;
        
        private string createUserField;
        
        private System.Nullable<System.DateTime> createDateField;
        
        private string memoField;
        
        private System.Nullable<int> poDetailIdField;
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> Seq {
            get {
                return this.seqField;
            }
            set {
                this.seqField = value;
            }
        }
        
        /// <remarks/>
        public string BarCode {
            get {
                return this.barCodeField;
            }
            set {
                this.barCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LotNo {
            get {
                return this.lotNoField;
            }
            set {
                this.lotNoField = value;
            }
        }
        
        /// <remarks/>
        public string ItemCode {
            get {
                return this.itemCodeField;
            }
            set {
                this.itemCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ItemDescription {
            get {
                return this.itemDescriptionField;
            }
            set {
                this.itemDescriptionField = value;
            }
        }
        
        /// <remarks/>
        public string Uom {
            get {
                return this.uomField;
            }
            set {
                this.uomField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> UC {
            get {
                return this.ucField;
            }
            set {
                this.ucField = value;
            }
        }
        
        /// <remarks/>
        public decimal Qty {
            get {
                return this.qtyField;
            }
            set {
                this.qtyField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string SupplierCode {
            get {
                return this.supplierCodeField;
            }
            set {
                this.supplierCodeField = value;
            }
        }
        
        /// <remarks/>
        public string CreateUser {
            get {
                return this.createUserField;
            }
            set {
                this.createUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> CreateDate {
            get {
                return this.createDateField;
            }
            set {
                this.createDateField = value;
            }
        }
        
        /// <remarks/>
        public string Memo {
            get {
                return this.memoField;
            }
            set {
                this.memoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> PoDetailId {
            get {
                return this.poDetailIdField;
            }
            set {
                this.poDetailIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://com.LocalSystem.Webservice")]
    public partial class BarCode : BarCodeBase {
    }
}
