//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.4952
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://faurecia.com/lisa/kmp58")]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "http://faurecia.com/lisa/kmp58", IsNullable = false)]
public partial class ManifestFile
{

    private object[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("delivery", typeof(ManifestFileDelivery), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("fileEnd", typeof(ManifestFileFileEnd), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlElementAttribute("fileHeader", typeof(ManifestFileFileHeader), Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public object[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ManifestFileDelivery
{

    private ManifestFileDeliveryRecheader[] recheaderField;

    private ManifestFileDeliveryRecpos[] recposField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("recheader", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ManifestFileDeliveryRecheader[] recheader
    {
        get
        {
            return this.recheaderField;
        }
        set
        {
            this.recheaderField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("recpos", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ManifestFileDeliveryRecpos[] recpos
    {
        get
        {
            return this.recposField;
        }
        set
        {
            this.recposField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ManifestFileDeliveryRecheader
{

    private string tYPEField;

    private string mANPARTField;

    private string mURNField;

    private string eRPCODEField;

    private string pGCODEField;

    private string fAUCODEField;

    private string mANCODEField;

    private string fDCODEField;

    private string sERPCODEField;

    private string sDCODEField;

    private string mANTYPEField;

    private string mANINDField;

    private string rECEPTField;

    private string cUCODEField;

    private string cUCODNAMEField;

    private string cULOGIDField;

    private string sUCODEField;

    private string sUCODNAMEField;

    private string sULOGIDField;

    private string mANTITLEField;

    private string aRRIVALField;

    private string pICKUPField;

    private string sUNAMEField;

    private string sUCONTACTField;

    private string sUFAXField;

    private string fAUPLANTField;

    private string pOSTCODEField;

    private string cITYField;

    private string fAUCONTACTField;

    private string fAUFAXField;

    private string rOUTEField;

    private string mROUTEField;

    private string lOGPNAMEField;

    private string oRDERGField;

    private string fAUADDR1Field;

    private string fAUADDR2Field;

    private string fAUADDR3Field;

    private string fAUCTRYField;

    private string fAUTELField;

    private string sUPADDR1Field;

    private string sUPADDR2Field;

    private string sUPADDR3Field;

    private string sUPPCODField;

    private string sUPCITYField;

    private string sUPCTRYField;

    private string sUPTELField;

    private string iNVNBRField;

    private string tOTWEIGHTField;

    private string uNITWEIGHTField;

    private string tOTVOLField;

    private string uNITVOLField;

    private string tOTPALField;

    private string aRRIVAL1CDField;

    private string dEPART1CDField;

    private string aRRIVAL2CDField;

    private string dEPART2CDField;

    private string dELORDGRField;

    private string bLANKField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANPART
    {
        get
        {
            return this.mANPARTField;
        }
        set
        {
            this.mANPARTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MURN
    {
        get
        {
            return this.mURNField;
        }
        set
        {
            this.mURNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ERPCODE
    {
        get
        {
            return this.eRPCODEField;
        }
        set
        {
            this.eRPCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PGCODE
    {
        get
        {
            return this.pGCODEField;
        }
        set
        {
            this.pGCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUCODE
    {
        get
        {
            return this.fAUCODEField;
        }
        set
        {
            this.fAUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANCODE
    {
        get
        {
            return this.mANCODEField;
        }
        set
        {
            this.mANCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FDCODE
    {
        get
        {
            return this.fDCODEField;
        }
        set
        {
            this.fDCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SERPCODE
    {
        get
        {
            return this.sERPCODEField;
        }
        set
        {
            this.sERPCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SDCODE
    {
        get
        {
            return this.sDCODEField;
        }
        set
        {
            this.sDCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANTYPE
    {
        get
        {
            return this.mANTYPEField;
        }
        set
        {
            this.mANTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANIND
    {
        get
        {
            return this.mANINDField;
        }
        set
        {
            this.mANINDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RECEPT
    {
        get
        {
            return this.rECEPTField;
        }
        set
        {
            this.rECEPTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CUCODE
    {
        get
        {
            return this.cUCODEField;
        }
        set
        {
            this.cUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CUCODNAME
    {
        get
        {
            return this.cUCODNAMEField;
        }
        set
        {
            this.cUCODNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CULOGID
    {
        get
        {
            return this.cULOGIDField;
        }
        set
        {
            this.cULOGIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUCODE
    {
        get
        {
            return this.sUCODEField;
        }
        set
        {
            this.sUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUCODNAME
    {
        get
        {
            return this.sUCODNAMEField;
        }
        set
        {
            this.sUCODNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SULOGID
    {
        get
        {
            return this.sULOGIDField;
        }
        set
        {
            this.sULOGIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANTITLE
    {
        get
        {
            return this.mANTITLEField;
        }
        set
        {
            this.mANTITLEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARRIVAL
    {
        get
        {
            return this.aRRIVALField;
        }
        set
        {
            this.aRRIVALField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PICKUP
    {
        get
        {
            return this.pICKUPField;
        }
        set
        {
            this.pICKUPField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUNAME
    {
        get
        {
            return this.sUNAMEField;
        }
        set
        {
            this.sUNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUCONTACT
    {
        get
        {
            return this.sUCONTACTField;
        }
        set
        {
            this.sUCONTACTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUFAX
    {
        get
        {
            return this.sUFAXField;
        }
        set
        {
            this.sUFAXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUPLANT
    {
        get
        {
            return this.fAUPLANTField;
        }
        set
        {
            this.fAUPLANTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string POSTCODE
    {
        get
        {
            return this.pOSTCODEField;
        }
        set
        {
            this.pOSTCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY
    {
        get
        {
            return this.cITYField;
        }
        set
        {
            this.cITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUCONTACT
    {
        get
        {
            return this.fAUCONTACTField;
        }
        set
        {
            this.fAUCONTACTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUFAX
    {
        get
        {
            return this.fAUFAXField;
        }
        set
        {
            this.fAUFAXField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ROUTE
    {
        get
        {
            return this.rOUTEField;
        }
        set
        {
            this.rOUTEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MROUTE
    {
        get
        {
            return this.mROUTEField;
        }
        set
        {
            this.mROUTEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LOGPNAME
    {
        get
        {
            return this.lOGPNAMEField;
        }
        set
        {
            this.lOGPNAMEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ORDERG
    {
        get
        {
            return this.oRDERGField;
        }
        set
        {
            this.oRDERGField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUADDR1
    {
        get
        {
            return this.fAUADDR1Field;
        }
        set
        {
            this.fAUADDR1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUADDR2
    {
        get
        {
            return this.fAUADDR2Field;
        }
        set
        {
            this.fAUADDR2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUADDR3
    {
        get
        {
            return this.fAUADDR3Field;
        }
        set
        {
            this.fAUADDR3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUCTRY
    {
        get
        {
            return this.fAUCTRYField;
        }
        set
        {
            this.fAUCTRYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUTEL
    {
        get
        {
            return this.fAUTELField;
        }
        set
        {
            this.fAUTELField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPADDR1
    {
        get
        {
            return this.sUPADDR1Field;
        }
        set
        {
            this.sUPADDR1Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPADDR2
    {
        get
        {
            return this.sUPADDR2Field;
        }
        set
        {
            this.sUPADDR2Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPADDR3
    {
        get
        {
            return this.sUPADDR3Field;
        }
        set
        {
            this.sUPADDR3Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPPCOD
    {
        get
        {
            return this.sUPPCODField;
        }
        set
        {
            this.sUPPCODField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPCITY
    {
        get
        {
            return this.sUPCITYField;
        }
        set
        {
            this.sUPCITYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPCTRY
    {
        get
        {
            return this.sUPCTRYField;
        }
        set
        {
            this.sUPCTRYField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUPTEL
    {
        get
        {
            return this.sUPTELField;
        }
        set
        {
            this.sUPTELField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string INVNBR
    {
        get
        {
            return this.iNVNBRField;
        }
        set
        {
            this.iNVNBRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TOTWEIGHT
    {
        get
        {
            return this.tOTWEIGHTField;
        }
        set
        {
            this.tOTWEIGHTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UNITWEIGHT
    {
        get
        {
            return this.uNITWEIGHTField;
        }
        set
        {
            this.uNITWEIGHTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TOTVOL
    {
        get
        {
            return this.tOTVOLField;
        }
        set
        {
            this.tOTVOLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UNITVOL
    {
        get
        {
            return this.uNITVOLField;
        }
        set
        {
            this.uNITVOLField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TOTPAL
    {
        get
        {
            return this.tOTPALField;
        }
        set
        {
            this.tOTPALField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARRIVAL1CD
    {
        get
        {
            return this.aRRIVAL1CDField;
        }
        set
        {
            this.aRRIVAL1CDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DEPART1CD
    {
        get
        {
            return this.dEPART1CDField;
        }
        set
        {
            this.dEPART1CDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ARRIVAL2CD
    {
        get
        {
            return this.aRRIVAL2CDField;
        }
        set
        {
            this.aRRIVAL2CDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DEPART2CD
    {
        get
        {
            return this.dEPART2CDField;
        }
        set
        {
            this.dEPART2CDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DELORDGR
    {
        get
        {
            return this.dELORDGRField;
        }
        set
        {
            this.dELORDGRField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BLANK
    {
        get
        {
            return this.bLANKField;
        }
        set
        {
            this.bLANKField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ManifestFileDeliveryRecpos
{

    private string tYPEField;

    private string mANPARTField;

    private string mURNField;

    private string eRPCODEField;

    private string pGCODEField;

    private string fAUCODEField;

    private string mANCODEField;

    private string fDCODEField;

    private string sERPCODEField;

    private string sDCODEField;

    private string mANTYPEField;

    private string mANINDField;

    private string rECEPTField;

    private string cUCODEField;

    private string cULOGIDField;

    private string sUCODEField;

    private string sULOGIDField;

    private string pNUMBERField;

    private string sEBANGOField;

    private string pNUMINDField;

    private string dESCField;

    private string oLOTField;

    private string pCS_PUField;

    private string nB_PUField;

    private string lABELIDField;

    private string pACKTYPEField;

    private string sCODEField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TYPE
    {
        get
        {
            return this.tYPEField;
        }
        set
        {
            this.tYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANPART
    {
        get
        {
            return this.mANPARTField;
        }
        set
        {
            this.mANPARTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MURN
    {
        get
        {
            return this.mURNField;
        }
        set
        {
            this.mURNField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ERPCODE
    {
        get
        {
            return this.eRPCODEField;
        }
        set
        {
            this.eRPCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PGCODE
    {
        get
        {
            return this.pGCODEField;
        }
        set
        {
            this.pGCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FAUCODE
    {
        get
        {
            return this.fAUCODEField;
        }
        set
        {
            this.fAUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANCODE
    {
        get
        {
            return this.mANCODEField;
        }
        set
        {
            this.mANCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FDCODE
    {
        get
        {
            return this.fDCODEField;
        }
        set
        {
            this.fDCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SERPCODE
    {
        get
        {
            return this.sERPCODEField;
        }
        set
        {
            this.sERPCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SDCODE
    {
        get
        {
            return this.sDCODEField;
        }
        set
        {
            this.sDCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANTYPE
    {
        get
        {
            return this.mANTYPEField;
        }
        set
        {
            this.mANTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MANIND
    {
        get
        {
            return this.mANINDField;
        }
        set
        {
            this.mANINDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string RECEPT
    {
        get
        {
            return this.rECEPTField;
        }
        set
        {
            this.rECEPTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CUCODE
    {
        get
        {
            return this.cUCODEField;
        }
        set
        {
            this.cUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CULOGID
    {
        get
        {
            return this.cULOGIDField;
        }
        set
        {
            this.cULOGIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUCODE
    {
        get
        {
            return this.sUCODEField;
        }
        set
        {
            this.sUCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SULOGID
    {
        get
        {
            return this.sULOGIDField;
        }
        set
        {
            this.sULOGIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PNUMBER
    {
        get
        {
            return this.pNUMBERField;
        }
        set
        {
            this.pNUMBERField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SEBANGO
    {
        get
        {
            return this.sEBANGOField;
        }
        set
        {
            this.sEBANGOField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PNUMIND
    {
        get
        {
            return this.pNUMINDField;
        }
        set
        {
            this.pNUMINDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DESC
    {
        get
        {
            return this.dESCField;
        }
        set
        {
            this.dESCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string OLOT
    {
        get
        {
            return this.oLOTField;
        }
        set
        {
            this.oLOTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PCS_PU
    {
        get
        {
            return this.pCS_PUField;
        }
        set
        {
            this.pCS_PUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NB_PU
    {
        get
        {
            return this.nB_PUField;
        }
        set
        {
            this.nB_PUField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LABELID
    {
        get
        {
            return this.lABELIDField;
        }
        set
        {
            this.lABELIDField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PACKTYPE
    {
        get
        {
            return this.pACKTYPEField;
        }
        set
        {
            this.pACKTYPEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SCODE
    {
        get
        {
            return this.sCODEField;
        }
        set
        {
            this.sCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ManifestFileFileEnd
{

    private string c_endField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string c_end
    {
        get
        {
            return this.c_endField;
        }
        set
        {
            this.c_endField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ManifestFileFileHeader
{

    private string sTARTField;

    private string pCODEField;

    private string pDESCField;

    private string fILIDField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string START
    {
        get
        {
            return this.sTARTField;
        }
        set
        {
            this.sTARTField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PCODE
    {
        get
        {
            return this.pCODEField;
        }
        set
        {
            this.pCODEField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PDESC
    {
        get
        {
            return this.pDESCField;
        }
        set
        {
            this.pDESCField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FILID
    {
        get
        {
            return this.fILIDField;
        }
        set
        {
            this.fILIDField = value;
        }
    }
}
