//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Export Data Delivery Item
 * 
 * <p>Java class for DELVRY03.E1EDL35 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDL35">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="STAWN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="17"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EXPRF" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="5"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EXART" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="2"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HERKL" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="HERKR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="GRWRT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="15"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PREFE" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="E1EDL36" type="{}DELVRY03.E1EDL36" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDL35", propOrder = {
    "stawn",
    "exprf",
    "exart",
    "herkl",
    "herkr",
    "grwrt",
    "prefe",
    "e1EDL36"
})
public class DELVRY03E1EDL35 {

    @XmlElement(name = "STAWN")
    protected String stawn;
    @XmlElement(name = "EXPRF")
    protected String exprf;
    @XmlElement(name = "EXART")
    protected String exart;
    @XmlElement(name = "HERKL")
    protected String herkl;
    @XmlElement(name = "HERKR")
    protected String herkr;
    @XmlElement(name = "GRWRT")
    protected String grwrt;
    @XmlElement(name = "PREFE")
    protected String prefe;
    @XmlElement(name = "E1EDL36")
    protected DELVRY03E1EDL36 e1EDL36;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the stawn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTAWN() {
        return stawn;
    }

    /**
     * Sets the value of the stawn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTAWN(String value) {
        this.stawn = value;
    }

    /**
     * Gets the value of the exprf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXPRF() {
        return exprf;
    }

    /**
     * Sets the value of the exprf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXPRF(String value) {
        this.exprf = value;
    }

    /**
     * Gets the value of the exart property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEXART() {
        return exart;
    }

    /**
     * Sets the value of the exart property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEXART(String value) {
        this.exart = value;
    }

    /**
     * Gets the value of the herkl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHERKL() {
        return herkl;
    }

    /**
     * Sets the value of the herkl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHERKL(String value) {
        this.herkl = value;
    }

    /**
     * Gets the value of the herkr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHERKR() {
        return herkr;
    }

    /**
     * Sets the value of the herkr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHERKR(String value) {
        this.herkr = value;
    }

    /**
     * Gets the value of the grwrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGRWRT() {
        return grwrt;
    }

    /**
     * Sets the value of the grwrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGRWRT(String value) {
        this.grwrt = value;
    }

    /**
     * Gets the value of the prefe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPREFE() {
        return prefe;
    }

    /**
     * Sets the value of the prefe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPREFE(String value) {
        this.prefe = value;
    }

    /**
     * Gets the value of the e1EDL36 property.
     * 
     * @return
     *     possible object is
     *     {@link DELVRY03E1EDL36 }
     *     
     */
    public DELVRY03E1EDL36 getE1EDL36() {
        return e1EDL36;
    }

    /**
     * Sets the value of the e1EDL36 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELVRY03E1EDL36 }
     *     
     */
    public void setE1EDL36(DELVRY03E1EDL36 value) {
        this.e1EDL36 = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
