//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * IDoc: Deadline (delivery)
 * 
 * <p>Java class for DELVRY03.E1EDT13 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDT13">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="QUALF" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSTZW" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSTZW_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NTANF" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NTANZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NTEND" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="NTENZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TZONE_BEG" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ISDD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ISDZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IEDD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="8"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="IEDZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TZONE_END" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="6"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VORNR" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSTGA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSTGA_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EVENT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="EVENT_ALI" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="E1EDL40" type="{}DELVRY03.E1EDL40" minOccurs="0"/>
 *         &lt;element name="E1TXTH0" type="{}DELVRY03.E1TXTH0" maxOccurs="99" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDT13", propOrder = {
    "qualf",
    "vstzw",
    "vstzwbez",
    "ntanf",
    "ntanz",
    "ntend",
    "ntenz",
    "tzonebeg",
    "isdd",
    "isdz",
    "iedd",
    "iedz",
    "tzoneend",
    "vornr",
    "vstga",
    "vstgabez",
    "event",
    "eventali",
    "e1EDL40",
    "e1TXTH0"
})
public class DELVRY03E1EDT13 {

    @XmlElement(name = "QUALF")
    protected String qualf;
    @XmlElement(name = "VSTZW")
    protected String vstzw;
    @XmlElement(name = "VSTZW_BEZ")
    protected String vstzwbez;
    @XmlElement(name = "NTANF")
    protected String ntanf;
    @XmlElement(name = "NTANZ")
    protected String ntanz;
    @XmlElement(name = "NTEND")
    protected String ntend;
    @XmlElement(name = "NTENZ")
    protected String ntenz;
    @XmlElement(name = "TZONE_BEG")
    protected String tzonebeg;
    @XmlElement(name = "ISDD")
    protected String isdd;
    @XmlElement(name = "ISDZ")
    protected String isdz;
    @XmlElement(name = "IEDD")
    protected String iedd;
    @XmlElement(name = "IEDZ")
    protected String iedz;
    @XmlElement(name = "TZONE_END")
    protected String tzoneend;
    @XmlElement(name = "VORNR")
    protected String vornr;
    @XmlElement(name = "VSTGA")
    protected String vstga;
    @XmlElement(name = "VSTGA_BEZ")
    protected String vstgabez;
    @XmlElement(name = "EVENT")
    protected String event;
    @XmlElement(name = "EVENT_ALI")
    protected String eventali;
    @XmlElement(name = "E1EDL40")
    protected DELVRY03E1EDL40 e1EDL40;
    @XmlElement(name = "E1TXTH0")
    protected List<DELVRY03E1TXTH0> e1TXTH0;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the qualf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQUALF() {
        return qualf;
    }

    /**
     * Sets the value of the qualf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQUALF(String value) {
        this.qualf = value;
    }

    /**
     * Gets the value of the vstzw property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTZW() {
        return vstzw;
    }

    /**
     * Sets the value of the vstzw property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTZW(String value) {
        this.vstzw = value;
    }

    /**
     * Gets the value of the vstzwbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTZWBEZ() {
        return vstzwbez;
    }

    /**
     * Sets the value of the vstzwbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTZWBEZ(String value) {
        this.vstzwbez = value;
    }

    /**
     * Gets the value of the ntanf property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNTANF() {
        return ntanf;
    }

    /**
     * Sets the value of the ntanf property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNTANF(String value) {
        this.ntanf = value;
    }

    /**
     * Gets the value of the ntanz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNTANZ() {
        return ntanz;
    }

    /**
     * Sets the value of the ntanz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNTANZ(String value) {
        this.ntanz = value;
    }

    /**
     * Gets the value of the ntend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNTEND() {
        return ntend;
    }

    /**
     * Sets the value of the ntend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNTEND(String value) {
        this.ntend = value;
    }

    /**
     * Gets the value of the ntenz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNTENZ() {
        return ntenz;
    }

    /**
     * Sets the value of the ntenz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNTENZ(String value) {
        this.ntenz = value;
    }

    /**
     * Gets the value of the tzonebeg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTZONEBEG() {
        return tzonebeg;
    }

    /**
     * Sets the value of the tzonebeg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTZONEBEG(String value) {
        this.tzonebeg = value;
    }

    /**
     * Gets the value of the isdd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDD() {
        return isdd;
    }

    /**
     * Sets the value of the isdd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDD(String value) {
        this.isdd = value;
    }

    /**
     * Gets the value of the isdz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISDZ() {
        return isdz;
    }

    /**
     * Sets the value of the isdz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISDZ(String value) {
        this.isdz = value;
    }

    /**
     * Gets the value of the iedd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIEDD() {
        return iedd;
    }

    /**
     * Sets the value of the iedd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIEDD(String value) {
        this.iedd = value;
    }

    /**
     * Gets the value of the iedz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIEDZ() {
        return iedz;
    }

    /**
     * Sets the value of the iedz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIEDZ(String value) {
        this.iedz = value;
    }

    /**
     * Gets the value of the tzoneend property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTZONEEND() {
        return tzoneend;
    }

    /**
     * Sets the value of the tzoneend property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTZONEEND(String value) {
        this.tzoneend = value;
    }

    /**
     * Gets the value of the vornr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVORNR() {
        return vornr;
    }

    /**
     * Sets the value of the vornr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVORNR(String value) {
        this.vornr = value;
    }

    /**
     * Gets the value of the vstga property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTGA() {
        return vstga;
    }

    /**
     * Sets the value of the vstga property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTGA(String value) {
        this.vstga = value;
    }

    /**
     * Gets the value of the vstgabez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTGABEZ() {
        return vstgabez;
    }

    /**
     * Sets the value of the vstgabez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTGABEZ(String value) {
        this.vstgabez = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENT() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENT(String value) {
        this.event = value;
    }

    /**
     * Gets the value of the eventali property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEVENTALI() {
        return eventali;
    }

    /**
     * Sets the value of the eventali property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEVENTALI(String value) {
        this.eventali = value;
    }

    /**
     * Gets the value of the e1EDL40 property.
     * 
     * @return
     *     possible object is
     *     {@link DELVRY03E1EDL40 }
     *     
     */
    public DELVRY03E1EDL40 getE1EDL40() {
        return e1EDL40;
    }

    /**
     * Sets the value of the e1EDL40 property.
     * 
     * @param value
     *     allowed object is
     *     {@link DELVRY03E1EDL40 }
     *     
     */
    public void setE1EDL40(DELVRY03E1EDL40 value) {
        this.e1EDL40 = value;
    }

    /**
     * Gets the value of the e1TXTH0 property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the e1TXTH0 property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getE1TXTH0().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DELVRY03E1TXTH0 }
     * 
     * 
     */
    public List<DELVRY03E1TXTH0> getE1TXTH0() {
        if (e1TXTH0 == null) {
            e1TXTH0 = new ArrayList<DELVRY03E1TXTH0>();
        }
        return this.e1TXTH0;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
