//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * DG item data descriptions 1 (delivery)
 * 
 * <p>Java class for DELVRY03.E1EDD11 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDD11">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VKTRT" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="60"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGNA" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGRESD2" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGRESD" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGRESD3" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGREDMP" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="DGREDRQ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="132"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDD11", propOrder = {
    "vktrt",
    "dgna",
    "dgresd2",
    "dgresd",
    "dgresd3",
    "dgredmp",
    "dgredrq"
})
public class DELVRY03E1EDD11 {

    @XmlElement(name = "VKTRT")
    protected String vktrt;
    @XmlElement(name = "DGNA")
    protected String dgna;
    @XmlElement(name = "DGRESD2")
    protected String dgresd2;
    @XmlElement(name = "DGRESD")
    protected String dgresd;
    @XmlElement(name = "DGRESD3")
    protected String dgresd3;
    @XmlElement(name = "DGREDMP")
    protected String dgredmp;
    @XmlElement(name = "DGREDRQ")
    protected String dgredrq;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the vktrt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVKTRT() {
        return vktrt;
    }

    /**
     * Sets the value of the vktrt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVKTRT(String value) {
        this.vktrt = value;
    }

    /**
     * Gets the value of the dgna property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGNA() {
        return dgna;
    }

    /**
     * Sets the value of the dgna property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGNA(String value) {
        this.dgna = value;
    }

    /**
     * Gets the value of the dgresd2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGRESD2() {
        return dgresd2;
    }

    /**
     * Sets the value of the dgresd2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGRESD2(String value) {
        this.dgresd2 = value;
    }

    /**
     * Gets the value of the dgresd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGRESD() {
        return dgresd;
    }

    /**
     * Sets the value of the dgresd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGRESD(String value) {
        this.dgresd = value;
    }

    /**
     * Gets the value of the dgresd3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGRESD3() {
        return dgresd3;
    }

    /**
     * Sets the value of the dgresd3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGRESD3(String value) {
        this.dgresd3 = value;
    }

    /**
     * Gets the value of the dgredmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGREDMP() {
        return dgredmp;
    }

    /**
     * Sets the value of the dgredmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGREDMP(String value) {
        this.dgredmp = value;
    }

    /**
     * Gets the value of the dgredrq property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDGREDRQ() {
        return dgredrq;
    }

    /**
     * Sets the value of the dgredrq property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDGREDRQ(String value) {
        this.dgredrq = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
