//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Delivery Header Descriptions
 * 
 * <p>Java class for DELVRY03.E1EDL22 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDL22">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VSTEL_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VKORG_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LSTEL_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VKBUR_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LGNUM_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="INCO1_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ROUTE_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="VSBED_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRATY_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDL22", propOrder = {
    "vstelbez",
    "vkorgbez",
    "lstelbez",
    "vkburbez",
    "lgnumbez",
    "inco1BEZ",
    "routebez",
    "vsbedbez",
    "tratybez"
})
public class DELVRY03E1EDL22 {

    @XmlElement(name = "VSTEL_BEZ")
    protected String vstelbez;
    @XmlElement(name = "VKORG_BEZ")
    protected String vkorgbez;
    @XmlElement(name = "LSTEL_BEZ")
    protected String lstelbez;
    @XmlElement(name = "VKBUR_BEZ")
    protected String vkburbez;
    @XmlElement(name = "LGNUM_BEZ")
    protected String lgnumbez;
    @XmlElement(name = "INCO1_BEZ")
    protected String inco1BEZ;
    @XmlElement(name = "ROUTE_BEZ")
    protected String routebez;
    @XmlElement(name = "VSBED_BEZ")
    protected String vsbedbez;
    @XmlElement(name = "TRATY_BEZ")
    protected String tratybez;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the vstelbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSTELBEZ() {
        return vstelbez;
    }

    /**
     * Sets the value of the vstelbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSTELBEZ(String value) {
        this.vstelbez = value;
    }

    /**
     * Gets the value of the vkorgbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVKORGBEZ() {
        return vkorgbez;
    }

    /**
     * Sets the value of the vkorgbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVKORGBEZ(String value) {
        this.vkorgbez = value;
    }

    /**
     * Gets the value of the lstelbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLSTELBEZ() {
        return lstelbez;
    }

    /**
     * Sets the value of the lstelbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLSTELBEZ(String value) {
        this.lstelbez = value;
    }

    /**
     * Gets the value of the vkburbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVKBURBEZ() {
        return vkburbez;
    }

    /**
     * Sets the value of the vkburbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVKBURBEZ(String value) {
        this.vkburbez = value;
    }

    /**
     * Gets the value of the lgnumbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLGNUMBEZ() {
        return lgnumbez;
    }

    /**
     * Sets the value of the lgnumbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLGNUMBEZ(String value) {
        this.lgnumbez = value;
    }

    /**
     * Gets the value of the inco1BEZ property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getINCO1BEZ() {
        return inco1BEZ;
    }

    /**
     * Sets the value of the inco1BEZ property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setINCO1BEZ(String value) {
        this.inco1BEZ = value;
    }

    /**
     * Gets the value of the routebez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getROUTEBEZ() {
        return routebez;
    }

    /**
     * Sets the value of the routebez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setROUTEBEZ(String value) {
        this.routebez = value;
    }

    /**
     * Gets the value of the vsbedbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVSBEDBEZ() {
        return vsbedbez;
    }

    /**
     * Sets the value of the vsbedbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVSBEDBEZ(String value) {
        this.vsbedbez = value;
    }

    /**
     * Gets the value of the tratybez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRATYBEZ() {
        return tratybez;
    }

    /**
     * Sets the value of the tratybez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRATYBEZ(String value) {
        this.tratybez = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
