//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.05.02 at 10:27:02 ÏÂÎç CST 
//


package com.faurecia.model.delvry;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Deliv.Header Addit.Data Descriptions
 * 
 * <p>Java class for DELVRY03.E1EDL23 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DELVRY03.E1EDL23">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LFART_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LPRIO_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="BZIRK_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LIFSK_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="KDGRP_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRAGR_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="TRSPG_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="AULWE_BEZ" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="40"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="SEGMENT" use="required" type="{http://www.w3.org/2001/XMLSchema}string" fixed="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DELVRY03.E1EDL23", propOrder = {
    "lfartbez",
    "lpriobez",
    "bzirkbez",
    "lifskbez",
    "kdgrpbez",
    "tragrbez",
    "trspgbez",
    "aulwebez"
})
public class DELVRY03E1EDL23 {

    @XmlElement(name = "LFART_BEZ")
    protected String lfartbez;
    @XmlElement(name = "LPRIO_BEZ")
    protected String lpriobez;
    @XmlElement(name = "BZIRK_BEZ")
    protected String bzirkbez;
    @XmlElement(name = "LIFSK_BEZ")
    protected String lifskbez;
    @XmlElement(name = "KDGRP_BEZ")
    protected String kdgrpbez;
    @XmlElement(name = "TRAGR_BEZ")
    protected String tragrbez;
    @XmlElement(name = "TRSPG_BEZ")
    protected String trspgbez;
    @XmlElement(name = "AULWE_BEZ")
    protected String aulwebez;
    @XmlAttribute(name = "SEGMENT", required = true)
    protected String segment;

    /**
     * Gets the value of the lfartbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLFARTBEZ() {
        return lfartbez;
    }

    /**
     * Sets the value of the lfartbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLFARTBEZ(String value) {
        this.lfartbez = value;
    }

    /**
     * Gets the value of the lpriobez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLPRIOBEZ() {
        return lpriobez;
    }

    /**
     * Sets the value of the lpriobez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLPRIOBEZ(String value) {
        this.lpriobez = value;
    }

    /**
     * Gets the value of the bzirkbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBZIRKBEZ() {
        return bzirkbez;
    }

    /**
     * Sets the value of the bzirkbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBZIRKBEZ(String value) {
        this.bzirkbez = value;
    }

    /**
     * Gets the value of the lifskbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLIFSKBEZ() {
        return lifskbez;
    }

    /**
     * Sets the value of the lifskbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLIFSKBEZ(String value) {
        this.lifskbez = value;
    }

    /**
     * Gets the value of the kdgrpbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKDGRPBEZ() {
        return kdgrpbez;
    }

    /**
     * Sets the value of the kdgrpbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKDGRPBEZ(String value) {
        this.kdgrpbez = value;
    }

    /**
     * Gets the value of the tragrbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRAGRBEZ() {
        return tragrbez;
    }

    /**
     * Sets the value of the tragrbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRAGRBEZ(String value) {
        this.tragrbez = value;
    }

    /**
     * Gets the value of the trspgbez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTRSPGBEZ() {
        return trspgbez;
    }

    /**
     * Sets the value of the trspgbez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTRSPGBEZ(String value) {
        this.trspgbez = value;
    }

    /**
     * Gets the value of the aulwebez property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAULWEBEZ() {
        return aulwebez;
    }

    /**
     * Sets the value of the aulwebez property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAULWEBEZ(String value) {
        this.aulwebez = value;
    }

    /**
     * Gets the value of the segment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSEGMENT() {
        if (segment == null) {
            return "1";
        } else {
            return segment;
        }
    }

    /**
     * Sets the value of the segment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSEGMENT(String value) {
        this.segment = value;
    }

}
